//! MakerNotes tag definitions for major camera manufacturers.
//!
//! Covers the most common maker note tags for Canon, Nikon, Sony,
//! Olympus, Pentax, Panasonic, Fujifilm, Samsung.

use crate::metadata::makernotes::Manufacturer;

/// Lookup tag name by manufacturer and tag ID.
pub fn lookup(manufacturer: Manufacturer, tag_id: u16) -> (&'static str, &'static str) {
    let table = match manufacturer {
        Manufacturer::Canon => &CANON_TAGS[..],
        Manufacturer::Nikon | Manufacturer::NikonOld => &NIKON_TAGS[..],
        Manufacturer::Sony => &SONY_TAGS[..],
        Manufacturer::Pentax => &PENTAX_TAGS[..],
        Manufacturer::Olympus | Manufacturer::OlympusNew => &OLYMPUS_TAGS[..],
        Manufacturer::Panasonic => &PANASONIC_TAGS[..],
        Manufacturer::Fujifilm => &FUJIFILM_TAGS[..],
        Manufacturer::Samsung => &SAMSUNG_TAGS[..],
        Manufacturer::Sigma => &SIGMA_TAGS[..],
        Manufacturer::Casio => &CASIO_TAGS[..],
        Manufacturer::Ricoh | Manufacturer::Minolta | Manufacturer::Apple
        | Manufacturer::Google | Manufacturer::DJI => &[][..], // Use generated tables
        Manufacturer::Unknown => return (
            &"Unknown",
            &"Unknown",
        ),
    };

    for &(id, name, desc) in table {
        if id == tag_id {
            return (name, desc);
        }
    }

    // Fallback to generated tables
    let gen_table = match manufacturer {
        Manufacturer::Canon => Some(&super::generated::GENERATED_CANON_TAGS[..]),
        Manufacturer::Nikon | Manufacturer::NikonOld => Some(&super::generated::GENERATED_NIKON_TAGS[..]),
        Manufacturer::Sony => Some(&super::generated::GENERATED_SONY_TAGS[..]),
        Manufacturer::Olympus | Manufacturer::OlympusNew => Some(&super::generated::GENERATED_OLYMPUS_TAGS[..]),
        Manufacturer::Pentax => Some(&super::generated::GENERATED_PENTAX_TAGS[..]),
        Manufacturer::Panasonic => Some(&super::generated::GENERATED_PANASONIC_TAGS[..]),
        Manufacturer::Fujifilm => Some(&super::generated::GENERATED_FUJIFILM_TAGS[..]),
        Manufacturer::Samsung => Some(&super::generated::GENERATED_SAMSUNG_TAGS[..]),
        _ => None,
    };

    if let Some(gen) = gen_table {
        for &(id, name) in gen {
            if id == tag_id {
                return (name, name);
            }
        }
    }

    ("Unknown", "Unknown MakerNote Tag")
}

// Tag table format: (tag_id, name, description)

static CANON_TAGS: &[(u16, &str, &str)] = &[
    (0x0001, "CanonCameraSettings", "Camera Settings"),
    (0x0002, "CanonFocalLength", "Focal Length"),
    (0x0003, "CanonFlashInfo", "Flash Info"),
    (0x0004, "CanonShotInfo", "Shot Info"),
    (0x0005, "CanonPanorama", "Panorama"),
    (0x0006, "CanonImageType", "Image Type"),
    (0x0007, "CanonFirmwareVersion", "Firmware Version"),
    (0x0008, "FileNumber", "File Number"),
    (0x0009, "OwnerName", "Owner Name"),
    (0x000A, "CanonColorInfo1", "Color Data 1"),
    (0x000C, "SerialNumber", "Serial Number"),
    (0x000D, "CanonCameraInfo", "Camera Info"),
    (0x000E, "CanonFileLength", "File Length"),
    (0x000F, "CustomFunctions", "Custom Functions"),
    (0x0010, "CanonModelID", "Model ID"),
    (0x0011, "MovieInfo", "Movie Info"),
    (0x0012, "CanonAFInfo", "AF Info"),
    (0x0013, "ThumbnailImageValidArea", "Thumbnail Valid Area"),
    (0x0015, "SerialNumberFormat", "Serial Number Format"),
    (0x001A, "SuperMacro", "Super Macro"),
    (0x001C, "DateStampMode", "Date Stamp Mode"),
    (0x001D, "MyColors", "My Colors"),
    (0x001E, "FirmwareRevision", "Firmware Revision"),
    (0x0023, "Categories", "Categories"),
    (0x0024, "FaceDetect1", "Face Detect 1"),
    (0x0025, "FaceDetect2", "Face Detect 2"),
    (0x0026, "CanonAFInfo2", "AF Info 2"),
    (0x0028, "ImageUniqueID", "Image Unique ID"),
    (0x002F, "WBShiftAB_GM", "WB Shift AB/GM"),
    (0x0035, "TimeInfo", "Time Info"),
    (0x0038, "BatteryType", "Battery Type"),
    (0x003C, "AFInfo3", "AF Info 3"),
    (0x0093, "CanonSerialInfo", "Serial Number Info"),
    (0x0095, "LensModel", "Lens Model"),
    (0x0096, "InternalSerialNumber", "Internal Serial Number"),
    (0x0097, "DustRemovalData", "Dust Removal Data"),
    (0x0098, "CropInfo", "Crop Info"),
    (0x0099, "CustomFunctions2", "Custom Functions 2"),
    (0x009A, "AspectInfo", "Aspect Info"),
    (0x00A0, "ProcessingInfo", "Processing Info"),
    (0x00AA, "MeasuredColor", "Measured Color"),
    (0x00B4, "ColorSpace", "Color Space"),
    (0x00D0, "VRDOffset", "VRD Offset"),
    (0x00E0, "SensorInfo", "Sensor Info"),
    (0x4001, "ColorData", "Color Data"),
    (0x4002, "CRWParam", "CRW Param"),
    (0x4003, "ColorInfo", "Color Info"),
    (0x4005, "Flavor", "Flavor"),
    (0x4008, "PictureStyleUserDef", "Picture Style User Def"),
    (0x4009, "PictureStylePC", "Picture Style PC"),
    (0x4010, "CustomPictureStyleFileName", "Custom Picture Style"),
    (0x4013, "AFMicroAdj", "AF Micro Adjust"),
    (0x4015, "VignettingCorr", "Vignetting Correction"),
    (0x4016, "VignettingCorr2", "Vignetting Correction 2"),
    (0x4018, "LightingOpt", "Lighting Optimization"),
    (0x4019, "LensInfo", "Lens Info"),
    (0x4020, "AmbienceInfo", "Ambience Info"),
    (0x4024, "FilterInfo", "Filter Info"),
    (0x4025, "HDRInfo", "HDR Info"),
    (0x4028, "AFConfig", "AF Config"),
    (0x403F, "RawBurstModeRoll", "Raw Burst Mode Roll"),
];

static NIKON_TAGS: &[(u16, &str, &str)] = &[
    (0x0001, "MakerNoteVersion", "Maker Note Version"),
    (0x0002, "ISO", "ISO"),
    (0x0003, "ColorMode", "Color Mode"),
    (0x0004, "Quality", "Quality"),
    (0x0005, "WhiteBalance", "White Balance"),
    (0x0006, "Sharpness", "Sharpness"),
    (0x0007, "FocusMode", "Focus Mode"),
    (0x0008, "FlashSetting", "Flash Setting"),
    (0x0009, "FlashType", "Flash Type"),
    (0x000B, "WhiteBalanceFineTune", "White Balance Fine Tune"),
    (0x000C, "WBRBLevels", "WB RB Levels"),
    (0x000D, "ProgramShift", "Program Shift"),
    (0x000E, "ExposureDifference", "Exposure Difference"),
    (0x000F, "ISOSelection", "ISO Selection"),
    (0x0010, "DataDump", "Data Dump"),
    (0x0011, "PreviewIFD", "Preview IFD"),
    (0x0012, "FlashExposureComp", "Flash Exposure Comp"),
    (0x0013, "ISOSetting", "ISO Setting"),
    (0x0016, "ImageBoundary", "Image Boundary"),
    (0x0017, "ExternalFlashExposureComp", "External Flash Comp"),
    (0x0018, "FlashExposureBracketValue", "Flash Bracket Value"),
    (0x0019, "ExposureBracketValue", "Exposure Bracket Value"),
    (0x001A, "ImageProcessing", "Image Processing"),
    (0x001B, "CropHiSpeed", "Crop Hi Speed"),
    (0x001C, "ExposureTuning", "Exposure Tuning"),
    (0x001D, "SerialNumber", "Serial Number"),
    (0x001E, "ColorSpace", "Color Space"),
    (0x001F, "VRInfo", "VR Info"),
    (0x0020, "ImageAuthentication", "Image Authentication"),
    (0x0021, "FaceDetect", "Face Detect"),
    (0x0022, "ActiveD-Lighting", "Active D-Lighting"),
    (0x0023, "PictureControlData", "Picture Control"),
    (0x0024, "WorldTime", "World Time"),
    (0x0025, "ISOInfo", "ISO Info"),
    (0x002A, "VignetteControl", "Vignette Control"),
    (0x002B, "DistortInfo", "Distort Info"),
    (0x002C, "UnknownInfo", "Unknown Info"),
    (0x0032, "UnknownInfo2", "Unknown Info 2"),
    (0x0034, "ShutterMode", "Shutter Mode"),
    (0x0035, "HDRInfo", "HDR Info"),
    (0x0039, "LocationInfo", "Location Info"),
    (0x003D, "BlackLevel", "Black Level"),
    (0x0045, "CropArea", "Crop Area"),
    (0x004E, "NikonSettings", "Nikon Settings"),
    (0x0080, "ImageAdjustment", "Image Adjustment"),
    (0x0081, "ToneComp", "Tone Compensation"),
    (0x0082, "AuxiliaryLens", "Auxiliary Lens"),
    (0x0083, "LensType", "Lens Type"),
    (0x0084, "Lens", "Lens"),
    (0x0085, "ManualFocusDistance", "Manual Focus Distance"),
    (0x0086, "DigitalZoom", "Digital Zoom"),
    (0x0087, "FlashMode", "Flash Mode"),
    (0x0088, "AFInfo", "AF Info"),
    (0x0089, "ShootingMode", "Shooting Mode"),
    (0x008B, "LensFStops", "Lens F-Stops"),
    (0x008C, "ContrastCurve", "Contrast Curve"),
    (0x008D, "ColorHue", "Color Hue"),
    (0x008F, "SceneMode", "Scene Mode"),
    (0x0090, "LightSource", "Light Source"),
    (0x0091, "ShotInfo", "Shot Info"),
    (0x0092, "HueAdjustment", "Hue Adjustment"),
    (0x0093, "NEFCompression", "NEF Compression"),
    (0x0094, "Saturation", "Saturation"),
    (0x0095, "NoiseReduction", "Noise Reduction"),
    (0x0096, "NEFLinearizationTable", "NEF Linearization Table"),
    (0x0097, "ColorBalance", "Color Balance"),
    (0x0098, "LensData", "Lens Data"),
    (0x0099, "RawImageCenter", "Raw Image Center"),
    (0x009A, "SensorPixelSize", "Sensor Pixel Size"),
    (0x009C, "SceneAssist", "Scene Assist"),
    (0x009E, "RetouchHistory", "Retouch History"),
    (0x00A0, "SerialNumber2", "Serial Number 2"),
    (0x00A2, "ImageDataSize", "Image Data Size"),
    (0x00A5, "ImageCount", "Image Count"),
    (0x00A6, "DeletedImageCount", "Deleted Image Count"),
    (0x00A7, "ShutterCount", "Shutter Count"),
    (0x00A8, "FlashInfo", "Flash Info"),
    (0x00A9, "ImageOptimization", "Image Optimization"),
    (0x00AA, "Saturation2", "Saturation 2"),
    (0x00AB, "VariProgram", "Vari Program"),
    (0x00AC, "ImageStabilization", "Image Stabilization"),
    (0x00AD, "AFResponse", "AF Response"),
    (0x00B0, "MultiExposure", "Multi Exposure"),
    (0x00B1, "HighISONoiseReduction", "High ISO Noise Reduction"),
    (0x00B3, "ToningEffect", "Toning Effect"),
    (0x00B7, "AFInfo2", "AF Info 2"),
    (0x00B8, "FileInfo", "File Info"),
    (0x00B9, "AFTune", "AF Tune"),
    (0x00C3, "BarometerInfo", "Barometer Info"),
    (0x0E00, "PrintIM", "Print Image Matching"),
    (0x0E01, "NikonCaptureData", "Nikon Capture Data"),
    (0x0E09, "NikonCaptureVersion", "Nikon Capture Version"),
    (0x0E0E, "NikonCaptureOffsets", "Nikon Capture Offsets"),
    (0x0E10, "NikonScanIFD", "Nikon Scan IFD"),
    (0x0E22, "NikonCaptureEditVersions", "Nikon Capture Edit Versions"),
];

static SONY_TAGS: &[(u16, &str, &str)] = &[
    (0x0102, "Quality", "Quality"),
    (0x0104, "FlashExposureComp", "Flash Exposure Comp"),
    (0x0105, "Teleconverter", "Teleconverter"),
    (0x0112, "WhiteBalanceFineTune", "White Balance Fine Tune"),
    (0x0114, "CameraSettings", "Camera Settings"),
    (0x0115, "WhiteBalance", "White Balance"),
    (0x0116, "ExtraInfo", "Extra Info"),
    (0x0E00, "PrintIM", "Print Image Matching"),
    (0x1000, "MultiBurstMode", "Multi Burst Mode"),
    (0x1001, "MultiBurstImageWidth", "Multi Burst Image Width"),
    (0x1002, "MultiBurstImageHeight", "Multi Burst Image Height"),
    (0x1003, "Panorama", "Panorama"),
    (0x2001, "PreviewImage", "Preview Image"),
    (0x2002, "Rating", "Rating"),
    (0x2004, "Contrast", "Contrast"),
    (0x2005, "Saturation", "Saturation"),
    (0x2006, "Sharpness", "Sharpness"),
    (0x2007, "Brightness", "Brightness"),
    (0x2008, "LongExposureNoiseReduction", "Long Exposure NR"),
    (0x2009, "HighISONoiseReduction", "High ISO NR"),
    (0x200A, "HDR", "HDR"),
    (0x200B, "MultiFrameNoiseReduction", "Multi Frame NR"),
    (0x200E, "PictureEffect", "Picture Effect"),
    (0x200F, "SoftSkinEffect", "Soft Skin Effect"),
    (0x2010, "VignettingCorrection", "Vignetting Correction"),
    (0x2011, "LateralChromaticAberration", "Lateral CA"),
    (0x2012, "DistortionCorrection", "Distortion Correction"),
    (0x2013, "WBShiftAB_GM", "WB Shift AB/GM"),
    (0x2016, "AutoPortraitFramed", "Auto Portrait Framed"),
    (0x2017, "FlashAction", "Flash Action"),
    (0x201B, "FocusMode", "Focus Mode"),
    (0x201C, "AFAreaMode", "AF Area Mode"),
    (0x201E, "AFPointSelected", "AF Point Selected"),
    (0x3000, "ShotInfo", "Shot Info"),
    (0xB000, "FileFormat", "File Format"),
    (0xB001, "SonyModelID", "Sony Model ID"),
    (0xB020, "CreativeStyle", "Creative Style"),
    (0xB021, "ColorTemperature", "Color Temperature"),
    (0xB022, "ColorCompensationFilter", "Color Comp Filter"),
    (0xB023, "SceneMode", "Scene Mode"),
    (0xB024, "ZoneMatching", "Zone Matching"),
    (0xB025, "DynamicRangeOptimizer", "Dynamic Range Optimizer"),
    (0xB026, "ImageStabilization", "Image Stabilization"),
    (0xB027, "LensType", "Lens Type"),
    (0xB028, "MinoltaMakerNote", "Minolta Maker Note"),
    (0xB029, "ColorMode", "Color Mode"),
    (0xB02B, "FullImageSize", "Full Image Size"),
    (0xB040, "Macro", "Macro"),
    (0xB041, "ExposureMode", "Exposure Mode"),
    (0xB042, "FocusMode2", "Focus Mode 2"),
    (0xB043, "AFMode", "AF Mode"),
    (0xB044, "AFIlluminator", "AF Illuminator"),
    (0xB047, "JPEGQuality", "JPEG Quality"),
    (0xB048, "FlashLevel", "Flash Level"),
    (0xB049, "ReleaseMode", "Release Mode"),
    (0xB04A, "SequenceNumber", "Sequence Number"),
    (0xB04B, "Anti-Blur", "Anti-Blur"),
    (0xB04E, "LongExposureNoiseReduction2", "Long Exposure NR 2"),
    (0xB04F, "DynamicRangeOptimizer2", "DRO 2"),
    (0xB050, "HighISONoiseReduction2", "High ISO NR 2"),
    (0xB052, "IntelligentAuto", "Intelligent Auto"),
    (0xB054, "WhiteBalance2", "White Balance 2"),
];

static PENTAX_TAGS: &[(u16, &str, &str)] = &[
    (0x0000, "PentaxVersion", "Pentax Version"),
    (0x0001, "PentaxModelType", "Model Type"),
    (0x0002, "PreviewImageSize", "Preview Image Size"),
    (0x0003, "PreviewImageLength", "Preview Image Length"),
    (0x0004, "PreviewImageStart", "Preview Image Start"),
    (0x0005, "PentaxModelID", "Model ID"),
    (0x0006, "Date", "Date"),
    (0x0007, "Time", "Time"),
    (0x0008, "Quality", "Quality"),
    (0x0009, "PentaxImageSize", "Image Size"),
    (0x000B, "PictureMode", "Picture Mode"),
    (0x000C, "FlashMode", "Flash Mode"),
    (0x000D, "FocusMode", "Focus Mode"),
    (0x000E, "AFPointSelected", "AF Point Selected"),
    (0x000F, "AFPointsInFocus", "AF Points In Focus"),
    (0x0010, "FocusPosition", "Focus Position"),
    (0x0012, "ExposureTime", "Exposure Time"),
    (0x0013, "FNumber", "F Number"),
    (0x0014, "ISO", "ISO"),
    (0x0016, "ExposureCompensation", "Exposure Compensation"),
    (0x0017, "MeteringMode", "Metering Mode"),
    (0x0018, "AutoBracketing", "Auto Bracketing"),
    (0x0019, "WhiteBalance", "White Balance"),
    (0x001A, "WhiteBalanceMode", "White Balance Mode"),
    (0x001B, "BlueBalance", "Blue Balance"),
    (0x001C, "RedBalance", "Red Balance"),
    (0x001D, "FocalLength", "Focal Length"),
    (0x001E, "DigitalZoom", "Digital Zoom"),
    (0x001F, "Saturation", "Saturation"),
    (0x0020, "Contrast", "Contrast"),
    (0x0021, "Sharpness", "Sharpness"),
    (0x0022, "WorldTimeLocation", "World Time Location"),
    (0x0023, "HometownCity", "Hometown City"),
    (0x0024, "DestinationCity", "Destination City"),
    (0x0025, "HometownDST", "Hometown DST"),
    (0x0026, "DestinationDST", "Destination DST"),
    (0x0027, "DSPFirmwareVersion", "DSP Firmware Version"),
    (0x0028, "CPUFirmwareVersion", "CPU Firmware Version"),
    (0x0029, "FrameNumber", "Frame Number"),
    (0x003E, "LensType", "Lens Type"),
    (0x003F, "LensModel", "Lens Model"),
    (0x0047, "Temperature", "Temperature"),
    (0x0048, "AELock", "AE Lock"),
    (0x0049, "NoiseReduction", "Noise Reduction"),
    (0x004D, "FlashExposureComp", "Flash Exposure Comp"),
    (0x004F, "ImageTone", "Image Tone"),
    (0x0050, "ColorTemperature", "Color Temperature"),
    (0x005C, "ShakeReduction", "Shake Reduction"),
    (0x005D, "ShutterCount", "Shutter Count"),
    (0x0069, "DynamicRangeExpansion", "Dynamic Range Expansion"),
    (0x006B, "CrossProcess", "Cross Process"),
    (0x0072, "LensSerialNumber", "Lens Serial Number"),
    (0x0073, "SensorWidth", "Sensor Width"),
    (0x0074, "SensorHeight", "Sensor Height"),
    (0x0076, "LensID", "Lens ID"),
    (0x0200, "BlackPoint", "Black Point"),
    (0x0201, "WhitePoint", "White Point"),
    (0x0205, "ShotInfo", "Shot Info"),
    (0x0206, "AEInfo", "AE Info"),
    (0x0207, "LensInfo", "Lens Info"),
    (0x0208, "FlashInfo", "Flash Info"),
    (0x0209, "AEMeteringSegments", "AE Metering Segments"),
    (0x020D, "WB_RGGBLevels", "WB RGGB Levels"),
];

static OLYMPUS_TAGS: &[(u16, &str, &str)] = &[
    (0x0000, "MakerNoteVersion", "Maker Note Version"),
    (0x0001, "MinoltaCameraSettingsOld", "Camera Settings"),
    (0x0003, "MinoltaCameraSettings", "Camera Settings"),
    (0x0040, "CompressedImageSize", "Compressed Image Size"),
    (0x0081, "PreviewImageData", "Preview Image"),
    (0x0088, "PreviewImageStart", "Preview Image Start"),
    (0x0089, "PreviewImageLength", "Preview Image Length"),
    (0x0100, "ThumbnailImage", "Thumbnail Image"),
    (0x0104, "BodyFirmwareVersion", "Body Firmware Version"),
    (0x0200, "SpecialMode", "Special Mode"),
    (0x0201, "Quality", "Quality"),
    (0x0202, "Macro", "Macro"),
    (0x0203, "BWMode", "BW Mode"),
    (0x0204, "DigitalZoom", "Digital Zoom"),
    (0x0205, "FocalPlaneDiagonal", "Focal Plane Diagonal"),
    (0x0206, "LensDistortionParams", "Lens Distortion Params"),
    (0x0207, "CameraType", "Camera Type"),
    (0x0208, "TextInfo", "Text Info"),
    (0x0209, "CameraID", "Camera ID"),
    (0x020B, "EpsonImageWidth", "Image Width"),
    (0x020C, "EpsonImageHeight", "Image Height"),
    (0x020D, "EpsonSoftware", "Software"),
    (0x0300, "PreCaptureFrames", "Pre Capture Frames"),
    (0x0302, "OneTouchWB", "One Touch WB"),
    (0x0404, "SerialNumber", "Serial Number"),
    (0x1000, "ShutterSpeedValue", "Shutter Speed"),
    (0x1001, "ISOValue", "ISO"),
    (0x1002, "ApertureValue", "Aperture"),
    (0x1003, "BrightnessValue", "Brightness"),
    (0x1004, "FlashMode", "Flash Mode"),
    (0x1005, "FlashDevice", "Flash Device"),
    (0x1006, "ExposureCompensation", "Exposure Compensation"),
    (0x1007, "SensorTemperature", "Sensor Temperature"),
    (0x1008, "LensTemperature", "Lens Temperature"),
    (0x100B, "FocusMode", "Focus Mode"),
    (0x100C, "ManualFocusDistance", "Manual Focus Distance"),
    (0x100D, "ZoomStepCount", "Zoom Step Count"),
    (0x100E, "FocusStepCount", "Focus Step Count"),
    (0x100F, "Sharpness", "Sharpness"),
    (0x1010, "FlashChargeLevel", "Flash Charge Level"),
    (0x1011, "ColorMatrix", "Color Matrix"),
    (0x1012, "BlackLevel", "Black Level"),
    (0x1015, "WhiteBalanceMode", "White Balance Mode"),
    (0x1017, "RedBalance", "Red Balance"),
    (0x1018, "BlueBalance", "Blue Balance"),
    (0x101A, "SerialNumber2", "Serial Number 2"),
    (0x1023, "FlashExposureComp", "Flash Exposure Comp"),
    (0x1024, "InternalFlashTable", "Internal Flash Table"),
    (0x1025, "ExternalFlashGValue", "External Flash G Value"),
    (0x1026, "ExternalFlashBounce", "External Flash Bounce"),
    (0x1027, "ExternalFlashZoom", "External Flash Zoom"),
    (0x1028, "ExternalFlashMode", "External Flash Mode"),
    (0x1029, "Contrast", "Contrast"),
    (0x102A, "SharpnessFactor", "Sharpness Factor"),
    (0x102B, "ColorControl", "Color Control"),
    (0x102C, "ValidBits", "Valid Bits"),
    (0x102D, "CoringFilter", "Coring Filter"),
    (0x102E, "OlympusImageWidth", "Image Width"),
    (0x102F, "OlympusImageHeight", "Image Height"),
    (0x1034, "CompressionRatio", "Compression Ratio"),
    (0x1035, "PreviewImageValid", "Preview Image Valid"),
    (0x1036, "PreviewImageStart2", "Preview Image Start"),
    (0x1037, "PreviewImageLength2", "Preview Image Length"),
    (0x1038, "AFResult", "AF Result"),
    (0x1039, "CCDScanMode", "CCD Scan Mode"),
    (0x103A, "NoiseReduction", "Noise Reduction"),
    (0x103B, "FocusStepInfinity", "Focus Step Infinity"),
    (0x103C, "FocusStepNear", "Focus Step Near"),
    (0x103D, "LightValueCenter", "Light Value Center"),
    (0x103E, "LightValuePeriphery", "Light Value Periphery"),
    (0x2010, "Equipment", "Equipment"),
    (0x2020, "CameraSettings", "Camera Settings 2"),
    (0x2030, "RawDevelopment", "Raw Development"),
    (0x2031, "RawDev2", "Raw Development 2"),
    (0x2040, "ImageProcessing", "Image Processing"),
    (0x2050, "FocusInfo", "Focus Info"),
    (0x2100, "Olympus2100", "Olympus 2100"),
    (0x2200, "Olympus2200", "Olympus 2200"),
    (0x2300, "Olympus2300", "Olympus 2300"),
    (0x2400, "Olympus2400", "Olympus 2400"),
    (0x2500, "Olympus2500", "Olympus 2500"),
    (0x2600, "Olympus2600", "Olympus 2600"),
    (0x2700, "Olympus2700", "Olympus 2700"),
    (0x2800, "Olympus2800", "Olympus 2800"),
    (0x2900, "Olympus2900", "Olympus 2900"),
    (0x3000, "RawInfo", "Raw Info"),
    (0x4000, "MainInfo", "Main Info"),
];

static PANASONIC_TAGS: &[(u16, &str, &str)] = &[
    (0x0001, "ImageQuality", "Image Quality"),
    (0x0002, "FirmwareVersion", "Firmware Version"),
    (0x0003, "WhiteBalance", "White Balance"),
    (0x0007, "FocusMode", "Focus Mode"),
    (0x000F, "AFAreaMode", "AF Area Mode"),
    (0x001A, "ImageStabilization", "Image Stabilization"),
    (0x001C, "Macro", "Macro Mode"),
    (0x001F, "ShootingMode", "Shooting Mode"),
    (0x0020, "Audio", "Audio"),
    (0x0023, "WhiteBalanceBias", "White Balance Bias"),
    (0x0024, "FlashBias", "Flash Bias"),
    (0x0025, "InternalSerialNumber", "Internal Serial Number"),
    (0x0026, "PanasonicExifVersion", "Exif Version"),
    (0x0028, "ColorEffect", "Color Effect"),
    (0x0029, "TimeSincePowerOn", "Time Since Power On"),
    (0x002A, "BurstMode", "Burst Mode"),
    (0x002B, "SequenceNumber", "Sequence Number"),
    (0x002C, "ContrastMode", "Contrast Mode"),
    (0x002D, "NoiseReduction", "Noise Reduction"),
    (0x002E, "SelfTimer", "Self Timer"),
    (0x0030, "Rotation", "Rotation"),
    (0x0031, "AFAssistLamp", "AF Assist Lamp"),
    (0x0032, "ColorMode", "Color Mode"),
    (0x0033, "BabyAge", "Baby Age"),
    (0x0034, "OpticalZoomMode", "Optical Zoom Mode"),
    (0x0035, "ConversionLens", "Conversion Lens"),
    (0x0036, "TravelDay", "Travel Day"),
    (0x003A, "WorldTimestamp", "World Timestamp"),
    (0x003C, "Contrast", "Contrast"),
    (0x003D, "BracketSettings", "Bracket Settings"),
    (0x003E, "WBShiftAB", "WB Shift AB"),
    (0x003F, "WBShiftGM", "WB Shift GM"),
    (0x0040, "FlashCurtain", "Flash Curtain"),
    (0x0041, "LongExposureNoiseReduction", "Long Exposure NR"),
    (0x0042, "PanasonicImageWidth", "Image Width"),
    (0x0043, "PanasonicImageHeight", "Image Height"),
    (0x0044, "AFPointPosition", "AF Point Position"),
    (0x0045, "FaceDetInfo", "Face Detection Info"),
    (0x0046, "LensType", "Lens Type"),
    (0x0047, "LensSerialNumber", "Lens Serial Number"),
    (0x0048, "AccessoryType", "Accessory Type"),
    (0x0049, "AccessorySerialNumber", "Accessory Serial Number"),
    (0x004D, "LensFirmwareVersion", "Lens Firmware Version"),
    (0x0051, "LensType", "Lens Type"),
    (0x0052, "LensSerialNumber2", "Lens Serial Number 2"),
    (0x0059, "Transform", "Transform"),
    (0x005D, "IntelligentExposure", "Intelligent Exposure"),
    (0x0060, "LensFirmwareVersion2", "Lens Firmware"),
    (0x0061, "FaceRecInfo", "Face Recognition Info"),
    (0x0062, "FlashWarning", "Flash Warning"),
    (0x0065, "Title", "Title"),
    (0x0066, "BabyName", "Baby Name"),
    (0x0067, "Location", "Location"),
    (0x0069, "Country", "Country"),
    (0x006B, "State", "State"),
    (0x006D, "City", "City"),
    (0x006F, "Landmark", "Landmark"),
    (0x0070, "IntelligentResolution", "Intelligent Resolution"),
    (0x0077, "BurstSpeed", "Burst Speed"),
    (0x0079, "IntelligentDRange", "Intelligent D-Range"),
    (0x007C, "ClearRetouch", "Clear Retouch"),
    (0x0080, "City2", "City 2"),
    (0x0086, "ManometerPressure", "Barometric Pressure"),
    (0x0089, "PhotoStyle", "Photo Style"),
    (0x008A, "ShadingCompensation", "Shading Compensation"),
    (0x008C, "AccelerometerZ", "Accelerometer Z"),
    (0x008D, "AccelerometerX", "Accelerometer X"),
    (0x008E, "AccelerometerY", "Accelerometer Y"),
    (0x008F, "CameraOrientation", "Camera Orientation"),
    (0x0090, "RollAngle", "Roll Angle"),
    (0x0091, "PitchAngle", "Pitch Angle"),
    (0x0093, "SweepPanoramaDirection", "Sweep Panorama Direction"),
    (0x0094, "SweepPanoramaFieldOfView", "Sweep Panorama FOV"),
    (0x0096, "TimerRecording", "Timer Recording"),
    (0x009D, "InternalNDFilter", "Internal ND Filter"),
    (0x009E, "HDR", "HDR"),
    (0x009F, "ShutterType", "Shutter Type"),
    (0x00A3, "ClearRetouchValue", "Clear Retouch Value"),
    (0x00AB, "TouchAE", "Touch AE"),
    (0x0E00, "PrintIM", "Print Image Matching"),
    (0x8000, "MakerNoteVersion", "Maker Note Version"),
    (0x8001, "SceneMode", "Scene Mode"),
    (0x8004, "WBRedLevel", "WB Red Level"),
    (0x8005, "WBGreenLevel", "WB Green Level"),
    (0x8006, "WBBlueLevel", "WB Blue Level"),
    (0x8007, "FlashFired", "Flash Fired"),
    (0x8008, "TextStamp", "Text Stamp"),
    (0x8009, "TextStamp2", "Text Stamp 2"),
    (0x8010, "BabyAge2", "Baby Age 2"),
    (0x8012, "Transform2", "Transform 2"),
];

static FUJIFILM_TAGS: &[(u16, &str, &str)] = &[
    (0x0000, "Version", "Version"),
    (0x0010, "InternalSerialNumber", "Internal Serial Number"),
    (0x1000, "Quality", "Quality"),
    (0x1001, "Sharpness", "Sharpness"),
    (0x1002, "WhiteBalance", "White Balance"),
    (0x1003, "Saturation", "Saturation"),
    (0x1004, "Contrast", "Contrast"),
    (0x1005, "ColorTemperature", "Color Temperature"),
    (0x1006, "Contrast2", "Contrast 2"),
    (0x100A, "WhiteBalanceFineTune", "White Balance Fine Tune"),
    (0x100B, "NoiseReduction", "Noise Reduction"),
    (0x100E, "HighISONoiseReduction", "High ISO Noise Reduction"),
    (0x1010, "FujiFlashMode", "Flash Mode"),
    (0x1011, "FlashExposureComp", "Flash Exposure Comp"),
    (0x1020, "Macro", "Macro"),
    (0x1021, "FocusMode", "Focus Mode"),
    (0x1022, "AFMode", "AF Mode"),
    (0x1023, "FocusPixel", "Focus Pixel"),
    (0x1030, "SlowSync", "Slow Sync"),
    (0x1031, "PictureMode", "Picture Mode"),
    (0x1032, "ExposureCount", "Exposure Count"),
    (0x1033, "EXRAuto", "EXR Auto"),
    (0x1034, "EXRMode", "EXR Mode"),
    (0x1040, "ShadowTone", "Shadow Tone"),
    (0x1041, "HighlightTone", "Highlight Tone"),
    (0x1044, "DigitalZoom", "Digital Zoom"),
    (0x1045, "LensModulationOptimizer", "Lens Modulation Optimizer"),
    (0x1047, "GrainEffect", "Grain Effect"),
    (0x1048, "ColorChromeEffect", "Color Chrome Effect"),
    (0x1049, "BWAdjustment", "BW Adjustment"),
    (0x104D, "CropMode", "Crop Mode"),
    (0x104E, "ColorChromeFXBlue", "Color Chrome FX Blue"),
    (0x1050, "ShutterType", "Shutter Type"),
    (0x1100, "AutoBracketing", "Auto Bracketing"),
    (0x1101, "SequenceNumber", "Sequence Number"),
    (0x1103, "DriveSettings", "Drive Settings"),
    (0x1201, "AdvancedFilter", "Advanced Filter"),
    (0x1210, "ColorMode", "Color Mode"),
    (0x1300, "BlurWarning", "Blur Warning"),
    (0x1301, "FocusWarning", "Focus Warning"),
    (0x1302, "ExposureWarning", "Exposure Warning"),
    (0x1304, "GEImageSize", "GE Image Size"),
    (0x1400, "DynamicRange", "Dynamic Range"),
    (0x1401, "FilmMode", "Film Simulation"),
    (0x1402, "DynamicRangeSetting", "Dynamic Range Setting"),
    (0x1403, "DevelopmentDynamicRange", "Development Dynamic Range"),
    (0x1404, "MinFocalLength", "Min Focal Length"),
    (0x1405, "MaxFocalLength", "Max Focal Length"),
    (0x1406, "MaxApertureAtMinFocal", "Max Aperture At Min Focal"),
    (0x1407, "MaxApertureAtMaxFocal", "Max Aperture At Max Focal"),
    (0x140B, "AutoDynamicRange", "Auto Dynamic Range"),
    (0x1422, "ImageStabilization", "Image Stabilization"),
    (0x1431, "Rating", "Rating"),
    (0x1436, "ImageGeneration", "Image Generation"),
    (0x1438, "ImageCount", "Image Count"),
    (0x4100, "FacesDetected", "Faces Detected"),
    (0x4200, "NumFaceElements", "Num Face Elements"),
];

static SAMSUNG_TAGS: &[(u16, &str, &str)] = &[
    (0x0001, "MakerNoteVersion", "Maker Note Version"),
    (0x0002, "DeviceType", "Device Type"),
    (0x0003, "SamsungModelID", "Model ID"),
    (0x0021, "FaceDetect", "Face Detect"),
    (0x0030, "FaceRecognition", "Face Recognition"),
    (0x0040, "RawDataByteOrder", "Raw Data Byte Order"),
    (0x0050, "WhiteBalanceSetup", "White Balance Setup"),
    (0x0100, "FirmwareName", "Firmware Name"),
    (0x0101, "SerialNumber", "Serial Number"),
    (0xA001, "LensType", "Lens Type"),
    (0xA002, "LensModel", "Lens Model"),
    (0xA003, "LensFirmware", "Lens Firmware"),
    (0xA010, "SensorAreas", "Sensor Areas"),
    (0xA011, "ColorSpace", "Color Space"),
    (0xA012, "SmartRange", "Smart Range"),
    (0xA013, "ExposureBiasValue", "Exposure Bias"),
    (0xA014, "ISO", "ISO"),
    (0xA018, "ExposureTime", "Exposure Time"),
    (0xA019, "FNumber", "F Number"),
    (0xA01A, "FocalLengthIn35mmFormat", "Focal Length 35mm"),
    (0xA020, "EncryptionKey", "Encryption Key"),
    (0xA021, "WB_RGGBLevelsUncorrected", "WB RGGB Levels"),
    (0xA022, "WB_RGGBLevelsAuto", "WB RGGB Auto"),
    (0xA023, "WB_RGGBLevelsIlluminator1", "WB RGGB Illuminator 1"),
    (0xA024, "WB_RGGBLevelsIlluminator2", "WB RGGB Illuminator 2"),
    (0xA028, "WB_RGGBLevelsBlack", "WB RGGB Black"),
    (0xA030, "ColorMatrix", "Color Matrix"),
    (0xA031, "ColorMatrixSRGB", "Color Matrix sRGB"),
    (0xA032, "ColorMatrixAdobeRGB", "Color Matrix Adobe RGB"),
    (0xA040, "ToneCurve1", "Tone Curve 1"),
    (0xA041, "ToneCurve2", "Tone Curve 2"),
    (0xA042, "ToneCurve3", "Tone Curve 3"),
    (0xA043, "ToneCurve4", "Tone Curve 4"),
];

static SIGMA_TAGS: &[(u16, &str, &str)] = &[
    (0x0002, "SerialNumber", "Serial Number"),
    (0x0003, "DriveMode", "Drive Mode"),
    (0x0004, "ResolutionMode", "Resolution Mode"),
    (0x0005, "AFMode", "AF Mode"),
    (0x0006, "FocusSetting", "Focus Setting"),
    (0x0007, "WhiteBalance", "White Balance"),
    (0x0008, "ExposureMode", "Exposure Mode"),
    (0x0009, "MeteringMode", "Metering Mode"),
    (0x000A, "LensFocalRange", "Lens Focal Range"),
    (0x000B, "ColorSpace", "Color Space"),
    (0x000C, "ExposureCompensation", "Exposure Compensation"),
    (0x000D, "Contrast", "Contrast"),
    (0x000E, "Shadow", "Shadow"),
    (0x000F, "Highlight", "Highlight"),
    (0x0010, "Saturation", "Saturation"),
    (0x0011, "Sharpness", "Sharpness"),
    (0x0012, "X3FillLight", "X3 Fill Light"),
    (0x0014, "ColorAdjustment", "Color Adjustment"),
    (0x0015, "AdjustmentMode", "Adjustment Mode"),
    (0x0016, "Quality", "Quality"),
    (0x0017, "Firmware", "Firmware"),
    (0x0018, "Software", "Software"),
    (0x0019, "AutoBracket", "Auto Bracket"),
];

static CASIO_TAGS: &[(u16, &str, &str)] = &[
    (0x0001, "RecordingMode", "Recording Mode"),
    (0x0002, "Quality", "Quality"),
    (0x0003, "FocusMode", "Focus Mode"),
    (0x0004, "FlashMode", "Flash Mode"),
    (0x0005, "FlashIntensity", "Flash Intensity"),
    (0x0006, "ObjectDistance", "Object Distance"),
    (0x0007, "WhiteBalance", "White Balance"),
    (0x000A, "DigitalZoom", "Digital Zoom"),
    (0x000B, "Sharpness", "Sharpness"),
    (0x000C, "Contrast", "Contrast"),
    (0x000D, "Saturation", "Saturation"),
    (0x0014, "ISO", "ISO"),
    (0x0015, "FirmwareDate", "Firmware Date"),
    (0x0016, "Enhancement", "Enhancement"),
    (0x0017, "ColorFilter", "Color Filter"),
    (0x0018, "AFPoint", "AF Point"),
    (0x0019, "FlashIntensity2", "Flash Intensity"),
    (0x0E00, "PrintIM", "Print IM"),
    (0x2001, "PreviewThumbnail", "Preview Thumbnail"),
    (0x3000, "RecordingMode2", "Recording Mode 2"),
    (0x3001, "Quality2", "Quality 2"),
    (0x3002, "FocusMode2", "Focus Mode 2"),
    (0x3003, "FlashMode2", "Flash Mode 2"),
    (0x3006, "ISO2", "ISO 2"),
    (0x3007, "WhiteBalance2", "White Balance 2"),
    (0x3008, "FocalLength", "Focal Length"),
    (0x3009, "Saturation2", "Saturation 2"),
    (0x300A, "Contrast2", "Contrast 2"),
    (0x300B, "Sharpness2", "Sharpness 2"),
    (0x300D, "ColorMode", "Color Mode"),
    (0x300E, "Enhancement2", "Enhancement 2"),
    (0x300F, "ColorFilter2", "Color Filter 2"),
    (0x3014, "CCDSensitivity", "CCD Sensitivity"),
    (0x3015, "LightingMode", "Lighting Mode"),
    (0x3016, "Quality3", "Quality 3"),
    (0x3017, "DynamicRange", "Dynamic Range"),
];
