//! Auto-generated decoders for Sony's ciphered MakerNote sub-tables.
//!
//! Source: ExifTool 3.87, lib/Image/ExifTool/Sony.pm.
//! Generated by scripts/gen_sony_ciphered.pl -- DO NOT EDIT MANUALLY.
//!
//! These tables are byte-substitution enciphered (see metadata::sony_decrypt)
//! and addressed by byte offset. Model conditions are carried over from the
//! Perl source verbatim rather than translated, so they cannot drift from it.
//!
//! Tables: 26, fields: 168.

use std::sync::LazyLock;

use regex_lite::Regex;

use crate::tags::conv_expr::{self, Val as Conv};
use crate::tag::{Tag, TagGroup, TagId};
use crate::value::Value;

static MODEL_RE_0: LazyLock<Regex> = LazyLock::new(|| Regex::new("^(DSC-(RX1|RX1R))\\b").unwrap());
static MODEL_RE_1: LazyLock<Regex> = LazyLock::new(|| Regex::new("^(SLT-A58|ILCE-(3000|3500)|NEX-3N|DSC-(HX300|HX50V|WX60|WX80|WX200|WX300|TX30))\\b").unwrap());
static MODEL_RE_2: LazyLock<Regex> = LazyLock::new(|| Regex::new("^(DSC-|Stellar)").unwrap());
static MODEL_RE_3: LazyLock<Regex> = LazyLock::new(|| Regex::new("^DSC-").unwrap());
static MODEL_RE_4: LazyLock<Regex> = LazyLock::new(|| Regex::new("^(DSC-RX100|Stellar)\\b").unwrap());
static MODEL_RE_5: LazyLock<Regex> = LazyLock::new(|| Regex::new("^(NEX-|Lunar|ILCE-)").unwrap());
static MODEL_RE_6: LazyLock<Regex> = LazyLock::new(|| Regex::new("^(SLT-A(65|77)V?|Lunar|NEX-(5N|7|VG20E))").unwrap());
static MODEL_RE_7: LazyLock<Regex> = LazyLock::new(|| Regex::new("^(SLT-A99|HV|ILCE-7)").unwrap());
static MODEL_RE_8: LazyLock<Regex> = LazyLock::new(|| Regex::new("^(ILCE-(5100|QX1)|ILCA-(68|77M2))").unwrap());
static MODEL_RE_9: LazyLock<Regex> = LazyLock::new(|| Regex::new("^(SLT-A(58|99V?)|HV|NEX-(3N|5R|5T|6|VG900|VG30E)|ILCE-([35]000|3500))\\b").unwrap());
static MODEL_RE_10: LazyLock<Regex> = LazyLock::new(|| Regex::new("^(SLT-A(37|57|65|77)V?|Lunar|NEX-(F3|5N|7|VG20E))").unwrap());
static MODEL_RE_11: LazyLock<Regex> = LazyLock::new(|| Regex::new("^(ILCA-)").unwrap());
static MODEL_RE_12: LazyLock<Regex> = LazyLock::new(|| Regex::new("^(ILCE-(7M3|7RM3A?))").unwrap());
static MODEL_RE_13: LazyLock<Regex> = LazyLock::new(|| Regex::new("^(ILCE-7|ILCE-9|ILCA-99)").unwrap());
static MODEL_RE_14: LazyLock<Regex> = LazyLock::new(|| Regex::new("^(ILCE-(6100A?|6400A?|6600|7C|7M3|7RM3A?|7RM4A?|9|9M2)|ZV-E10)\\b").unwrap());
static MODEL_RE_15: LazyLock<Regex> = LazyLock::new(|| Regex::new("^(ILCE-(7RM2|7SM2))").unwrap());
static MODEL_RE_16: LazyLock<Regex> = LazyLock::new(|| Regex::new("^(ILCE-(6300|6500)|ILCA-99M2)").unwrap());
static MODEL_RE_17: LazyLock<Regex> = LazyLock::new(|| Regex::new("^(ILCE-(1M2|6700|7CM2|7CR|7M5|7RM6)|ILME-FX2)").unwrap());
static MODEL_RE_18: LazyLock<Regex> = LazyLock::new(|| Regex::new("^(ILCE-(1M2|7M5|7RM6))").unwrap());
static MODEL_RE_19: LazyLock<Regex> = LazyLock::new(|| Regex::new("^(SLT-(A65|A77)V?|NEX-(5N|7|VG20E)|Lunar|DSC-(HX10V|HX20V|HX200V|TX20|TX55|TX300V|WX30|WX70))\\b").unwrap());
static MODEL_RE_20: LazyLock<Regex> = LazyLock::new(|| Regex::new("^(SLT-|HV|NEX-|Lunar|DSC-RX|Stellar)").unwrap());
static MODEL_RE_21: LazyLock<Regex> = LazyLock::new(|| Regex::new("^(ILCA-(68|77M2|99M2)|ILCE-(5000|5100|6000|6300|6500|7|7M2|7R|7RM2|7S|7SM2|QX1)|DSC-(HX350|HX400V|HX60V|HX80|HX90|HX90V|QX30|RX0|RX1RM2|RX10|RX10M2|RX10M3|RX100M3|RX100M4|RX100M5|WX220|WX350|WX500))\\b").unwrap());
static MODEL_RE_22: LazyLock<Regex> = LazyLock::new(|| Regex::new("^(DSC-RX1RM3|ILCE-(1|6700|7CM2|7CR|7M4|7M5|7RM5|7RM6|7SM3|9M3)|ILME-(FX2|FX3A?|FX30)|ZV-(E1|E10M2))\\b").unwrap());
static MODEL_RE_23: LazyLock<Regex> = LazyLock::new(|| Regex::new("^(DSC-(HX350|HX400V|HX60V|HX80|HX90|HX90V|QX30|RX10|RX10M2|RX10M3|RX100M3|RX100M4))\\b").unwrap());
static MODEL_RE_24: LazyLock<Regex> = LazyLock::new(|| Regex::new("^(DSC-(HX95|HX99|RX0|RX0M2|RX10M4|RX100M5|RX100M5A|RX100M6))\\b").unwrap());
static MODEL_RE_25: LazyLock<Regex> = LazyLock::new(|| Regex::new("^(DSC-RX100M7A?|ZV-(1A?|1F|1M2))\\b").unwrap());
static MODEL_RE_26: LazyLock<Regex> = LazyLock::new(|| Regex::new("^SLT-").unwrap());
static MODEL_RE_27: LazyLock<Regex> = LazyLock::new(|| Regex::new("^(SLT-|HV|ILCA-)").unwrap());
static MODEL_RE_28: LazyLock<Regex> = LazyLock::new(|| Regex::new("^(DSC-|ZV-)").unwrap());
static MODEL_RE_29: LazyLock<Regex> = LazyLock::new(|| Regex::new("^(ILCA-|ILCE-(7RM2|7M3|7RM3A?|7RM4A?|7SM2|6100|6300|6400|6500|6600|7C|9|9M2)|DSC-(HX80|HX90V|HX99|RX0|RX10M2|RX10M3|RX10M4|RX100M4|RX100M5|RX100M5A|RX100M6|RX100M7|WX500)|ZV-)").unwrap());
static MODEL_RE_30: LazyLock<Regex> = LazyLock::new(|| Regex::new("^(DSC-(RX100M5|RX100M5A|RX100M6|RX100M7|RX10M4|HX99)|ILCE-(6100|6400|6600|7C|7M3|7RM3A?|7RM4A?|9M2)|ZV-E10)").unwrap());
static MODEL_RE_31: LazyLock<Regex> = LazyLock::new(|| Regex::new("^(ILCE-(7RM2|7SM2)|DSC-(HX80|HX90V|RX10M2|RX10M3|RX100M4|WX500))").unwrap());
static MODEL_RE_32: LazyLock<Regex> = LazyLock::new(|| Regex::new("^(ILCE-(7|7R)|Lusso)$").unwrap());
static MODEL_RE_33: LazyLock<Regex> = LazyLock::new(|| Regex::new("^(DSC-)").unwrap());
static MODEL_RE_34: LazyLock<Regex> = LazyLock::new(|| Regex::new("^(ILCE-7M5)").unwrap());
static MODEL_RE_35: LazyLock<Regex> = LazyLock::new(|| Regex::new("^(ILCE-7RM6)").unwrap());
static MODEL_RE_36: LazyLock<Regex> = LazyLock::new(|| Regex::new("^(ILCE-(1|7SM3)|ILME-FX3A?)\\b").unwrap());
static MODEL_RE_37: LazyLock<Regex> = LazyLock::new(|| Regex::new("^(ILCE-7M4)").unwrap());
static MODEL_RE_38: LazyLock<Regex> = LazyLock::new(|| Regex::new("^(ILCE-(1M2|7CM2|7CR|7RM5)|ZV-E1)\\b").unwrap());
static MODEL_RE_39: LazyLock<Regex> = LazyLock::new(|| Regex::new("^(SLT-A(65|77)V?|NEX-(7|VG20E)|Lunar)$").unwrap());
static MODEL_RE_40: LazyLock<Regex> = LazyLock::new(|| Regex::new("^(SLT-A(37|57)|NEX-F3)$").unwrap());
static MODEL_RE_41: LazyLock<Regex> = LazyLock::new(|| Regex::new("^(DSC-(RX100M2|QX10|QX100))$").unwrap());
static MODEL_RE_42: LazyLock<Regex> = LazyLock::new(|| Regex::new("^(DSC-(QX30|RX10|RX100M3|HX60V|HX350|HX400V|WX220|WX350)|ILCE-(7(R|S|M2)?|[56]000|5100|QX1)|ILCA-(68|77M2))\\b").unwrap());
static MODEL_RE_43: LazyLock<Regex> = LazyLock::new(|| Regex::new("^(DSC-(RX0|RX1RM2|RX10M2|RX10M3|RX100M4|RX100M5|HX80|HX90V?|WX500)|ILCE-(6300|6500|7RM2|7SM2)|ILCA-99M2)\\b").unwrap());
static MODEL_RE_44: LazyLock<Regex> = LazyLock::new(|| Regex::new("^(ILCE-(6100A?|6400A?|6600|7C|7M3|7RM3A?|7RM4A?|9|9M2)|DSC-(RX10M4|RX100M6|RX100M5A|RX100M7A?|HX95|HX99|RX0M2)|ZV-(1[AF]?|1M2|E10))\\b").unwrap());
static MODEL_RE_45: LazyLock<Regex> = LazyLock::new(|| Regex::new("^(DSC-|Stellar|ILCE-(1|6100|6300|6400|6500|6600|6700|7C|7M3|7M4|7M5|7RM2|7RM3A?|7RM4A?|7RM5|7RM6|7SM2|7SM3|9|9M2)|ILCA-99M2|ILME-(FX2|FX3)|ZV-)").unwrap());
static MODEL_RE_46: LazyLock<Regex> = LazyLock::new(|| Regex::new("^(ILCE-(6100A?|6300|6400A?|6500|6600|7C|7M3|7RM2|7RM3A?|7RM4A?|7SM2|9|9M2)|ILCA-99M2|ZV-E10)\\b").unwrap());
static MODEL_RE_47: LazyLock<Regex> = LazyLock::new(|| Regex::new("^(ILCE-(1\\b|7M4|7RM5|7SM3)|ILME-FX3)").unwrap());
static MODEL_RE_48: LazyLock<Regex> = LazyLock::new(|| Regex::new("^(SLT-|HV)").unwrap());
static MODEL_RE_49: LazyLock<Regex> = LazyLock::new(|| Regex::new("^(NEX-|ILCE-|ILME-|Lunar|ZV-E10|ZV-E10M2|ZV-E1)\\b").unwrap());

fn u8_at(d: &[u8], o: usize) -> Option<u8> { d.get(o).copied() }
fn i8_at(d: &[u8], o: usize) -> Option<i8> { d.get(o).map(|v| *v as i8) }
fn u16_at(d: &[u8], o: usize) -> Option<u16> {
    Some(u16::from_le_bytes([*d.get(o)?, *d.get(o + 1)?]))
}
fn i16_at(d: &[u8], o: usize) -> Option<i16> {
    Some(i16::from_le_bytes([*d.get(o)?, *d.get(o + 1)?]))
}
fn u32_at(d: &[u8], o: usize) -> Option<u32> {
    Some(u32::from_le_bytes([*d.get(o)?, *d.get(o + 1)?, *d.get(o + 2)?, *d.get(o + 3)?]))
}
fn i32_at(d: &[u8], o: usize) -> Option<i32> {
    Some(i32::from_le_bytes([*d.get(o)?, *d.get(o + 1)?, *d.get(o + 2)?, *d.get(o + 3)?]))
}

fn mk(name: &str, print_value: String, raw: Value) -> Tag {
    Tag {
        id: TagId::Text(name.to_string()),
        name: name.to_string(),
        description: name.to_string(),
        group: TagGroup {
            family0: "MakerNotes".into(),
            family1: "Sony".into(),
            family2: "Camera".into(),
            family3: crate::tag::MAIN_DOCUMENT.into(),
        },
        raw_value: raw,
        print_value,
        priority: 0,
    }
}

/// Decode one deciphered Sony sub-table. `data` must already be deciphered.
#[must_use]
pub fn decode(table: &str, data: &[u8], model: &str) -> Vec<Tag> {
    match table {
        "Tag2010b" => tag2010b(data, model),
        "Tag2010c" => tag2010c(data, model),
        "Tag2010d" => tag2010d(data, model),
        "Tag2010e" => tag2010e(data, model),
        "Tag2010f" => tag2010f(data, model),
        "Tag2010g" => tag2010g(data, model),
        "Tag2010h" => tag2010h(data, model),
        "Tag2010i" => tag2010i(data, model),
        "Tag9050a" => tag9050a(data, model),
        "Tag9050b" => tag9050b(data, model),
        "Tag9050c" => tag9050c(data, model),
        "Tag9050d" => tag9050d(data, model),
        "Tag9400a" => tag9400a(data, model),
        "Tag9400b" => tag9400b(data, model),
        "Tag9400c" => tag9400c(data, model),
        "Tag9402" => tag9402(data, model),
        "Tag9403" => tag9403(data, model),
        "Tag9404a" => tag9404a(data, model),
        "Tag9404b" => tag9404b(data, model),
        "Tag9405a" => tag9405a(data, model),
        "Tag9405b" => tag9405b(data, model),
        "Tag9406" => tag9406(data, model),
        "Tag9406b" => tag9406b(data, model),
        "Tag940a" => tag940a(data, model),
        "Tag940c" => tag940c(data, model),
        "Tag9416" => tag9416(data, model),
        _ => Vec::new(),
    }
}

/// Which ciphered sub-table a Sony MakerNote tag uses on this body.
///
/// Mirrors the Condition chain on the Sony Main table entry.
#[must_use]
pub fn variant_for(tag: u16, model: &str) -> Option<&'static str> {
    match tag {
        0x2010 => {
            if MODEL_RE_39.is_match(model) { return Some("Tag2010b"); }
            if MODEL_RE_40.is_match(model) { return Some("Tag2010c"); }
            Some("Tag2010d")
        }
        0x9050 => {
            if !MODEL_RE_45.is_match(model) { return Some("Tag9050a"); }
            if MODEL_RE_46.is_match(model) { return Some("Tag9050b"); }
            if MODEL_RE_47.is_match(model) { return Some("Tag9050c"); }
            None
        }
        0x9400 => {
            Some("Tag9400a")
        }
        0x9403 => {
            Some("Tag9403")
        }
        0x940a => {
            if MODEL_RE_48.is_match(model) { return Some("Tag940a"); }
            None
        }
        0x940c => {
            if MODEL_RE_49.is_match(model) { return Some("Tag940c"); }
            None
        }
        0x9416 => {
            Some("Tag9416")
        }
        _ => None,
    }
}

fn tag2010b(data: &[u8], model: &str) -> Vec<Tag> {
    let _ = model;
    let mut tags = Vec::new();
    if let Some(v) = u32_at(data, 0x0) {
        tags.push(mk("SonyImageWidth3", v.to_string(), Value::I32(v as i32)));
    }
    tags
}

fn tag2010c(data: &[u8], model: &str) -> Vec<Tag> {
    let _ = model;
    let mut tags = Vec::new();
    if let Some(v) = u32_at(data, 0x0) {
        let mut cv = Conv::Num(f64::from(v));
        if let Some(x) = conv_expr::eval("$val/16", &cv) { cv = x; }
        let raw = Value::F64(cv.as_num());
        tags.push(mk("SonyImageWidth3", cv.as_string(), raw));
    }
    tags
}

fn tag2010d(data: &[u8], model: &str) -> Vec<Tag> {
    let _ = model;
    let mut tags = Vec::new();
    if let Some(v) = u32_at(data, 0x0) {
        tags.push(mk("SonyImageWidth3", v.to_string(), Value::I32(v as i32)));
    }
    tags
}

fn tag2010e(data: &[u8], model: &str) -> Vec<Tag> {
    let mut tags = Vec::new();
    if let Some(v) = u32_at(data, 0x0) {
        let mut cv = Conv::Num(f64::from(v));
        if let Some(x) = conv_expr::eval("$val/16", &cv) { cv = x; }
        let raw = Value::F64(cv.as_num());
        tags.push(mk("SonyImageWidth3", cv.as_string(), raw));
    }
    if MODEL_RE_0.is_match(model) {
        if let Some(v) = u16_at(data, 0x1258) {
            let mut cv = Conv::Num(f64::from(v));
            if let Some(x) = conv_expr::eval("100 * 2**(16 - $val/256)", &cv) { cv = x; }
            let raw = Value::F64(cv.as_num());
            if let Some(x) = conv_expr::eval("sprintf(\"%.0f\",$val)", &cv) { cv = x; }
            tags.push(mk("SonyISO", cv.as_string(), raw));
        }
    }
    if MODEL_RE_1.is_match(model) {
        if let Some(v) = u16_at(data, 0x1278) {
            let mut cv = Conv::Num(f64::from(v));
            if let Some(x) = conv_expr::eval("$val / 10", &cv) { cv = x; }
            let raw = Value::F64(cv.as_num());
            if let Some(x) = conv_expr::eval("sprintf(\"%.1f mm\",$val)", &cv) { cv = x; }
            tags.push(mk("FocalLength", cv.as_string(), raw));
        }
    }
    if MODEL_RE_1.is_match(model) {
        if let Some(v) = u16_at(data, 0x127a) {
            let mut cv = Conv::Num(f64::from(v));
            if let Some(x) = conv_expr::eval("$val / 10", &cv) { cv = x; }
            let raw = Value::F64(cv.as_num());
            if let Some(x) = conv_expr::eval("sprintf(\"%.1f mm\",$val)", &cv) { cv = x; }
            tags.push(mk("MinFocalLength", cv.as_string(), raw));
        }
    }
    if MODEL_RE_1.is_match(model) {
        if let Some(v) = u16_at(data, 0x127c) {
            let mut cv = Conv::Num(f64::from(v));
            if let Some(x) = conv_expr::eval("$val / 10", &cv) { cv = x; }
            let raw = Value::F64(cv.as_num());
            if let Some(x) = conv_expr::eval("sprintf(\"%.1f mm\",$val)", &cv) { cv = x; }
            tags.push(mk("MaxFocalLength", cv.as_string(), raw));
        }
    }
    if MODEL_RE_1.is_match(model) {
        if let Some(v) = u16_at(data, 0x1280) {
            let mut cv = Conv::Num(f64::from(v));
            if let Some(x) = conv_expr::eval("100 * 2**(16 - $val/256)", &cv) { cv = x; }
            let raw = Value::F64(cv.as_num());
            if let Some(x) = conv_expr::eval("sprintf(\"%.0f\",$val)", &cv) { cv = x; }
            tags.push(mk("SonyISO", cv.as_string(), raw));
        }
    }
    if !MODEL_RE_2.is_match(model) {
        if let Some(v) = u8_at(data, 0x1891) {
            let s = match v as i64 {
                0 => "Unknown".to_string(),
                1 => "APS-C".to_string(),
                2 => "Full-frame".to_string(),
                other => other.to_string(),
            };
            tags.push(mk("LensFormat", s, Value::I32(v as i32)));
        }
    }
    if let Some(v) = u8_at(data, 0x1892) {
        let s = match v as i64 {
            0 => "Unknown".to_string(),
            1 => "A-mount".to_string(),
            2 => "E-mount".to_string(),
            other => other.to_string(),
        };
        tags.push(mk("LensMount", s, Value::I32(v as i32)));
    }
    if !MODEL_RE_2.is_match(model) {
        if let Some(v) = u8_at(data, 0x1898) {
            tags.push(mk("DistortionCorrParamsPresent", v.to_string(), Value::I32(v as i32)));
        }
    }
    if !MODEL_RE_3.is_match(model) {
        if let Some(v) = u8_at(data, 0x1899) {
            tags.push(mk("DistortionCorrParamsNumber", v.to_string(), Value::I32(v as i32)));
        }
    }
    if !MODEL_RE_4.is_match(model) {
        if let Some(v) = u8_at(data, 0x192c) {
            let s = match v as i64 {
                0 => "16:9".to_string(),
                1 => "4:3".to_string(),
                2 => "3:2".to_string(),
                3 => "1:1".to_string(),
                5 => "Panorama".to_string(),
                other => other.to_string(),
            };
            tags.push(mk("AspectRatio", s, Value::I32(v as i32)));
        }
    }
    if MODEL_RE_4.is_match(model) {
        if let Some(v) = u8_at(data, 0x1a88) {
            let s = match v as i64 {
                0 => "16:9".to_string(),
                1 => "4:3".to_string(),
                2 => "3:2".to_string(),
                3 => "1:1".to_string(),
                5 => "Panorama".to_string(),
                other => other.to_string(),
            };
            tags.push(mk("AspectRatio", s, Value::I32(v as i32)));
        }
    }
    tags
}

fn tag2010f(data: &[u8], model: &str) -> Vec<Tag> {
    let _ = model;
    let mut tags = Vec::new();
    if let Some(v) = u32_at(data, 0x4) {
        tags.push(mk("SonyImageWidth3", v.to_string(), Value::I32(v as i32)));
    }
    if let Some(v) = u16_at(data, 0x1136) {
        let mut cv = Conv::Num(f64::from(v));
        if let Some(x) = conv_expr::eval("$val / 10", &cv) { cv = x; }
        let raw = Value::F64(cv.as_num());
        if let Some(x) = conv_expr::eval("sprintf(\"%.1f mm\",$val)", &cv) { cv = x; }
        tags.push(mk("MinFocalLength", cv.as_string(), raw));
    }
    if let Some(v) = u16_at(data, 0x1138) {
        let mut cv = Conv::Num(f64::from(v));
        if let Some(x) = conv_expr::eval("$val / 10", &cv) { cv = x; }
        let raw = Value::F64(cv.as_num());
        if let Some(x) = conv_expr::eval("sprintf(\"%.1f mm\",$val)", &cv) { cv = x; }
        tags.push(mk("MaxFocalLength", cv.as_string(), raw));
    }
    if let Some(v) = u16_at(data, 0x113c) {
        let mut cv = Conv::Num(f64::from(v));
        if let Some(x) = conv_expr::eval("100 * 2**(16 - $val/256)", &cv) { cv = x; }
        let raw = Value::F64(cv.as_num());
        if let Some(x) = conv_expr::eval("sprintf(\"%.0f\",$val)", &cv) { cv = x; }
        tags.push(mk("SonyISO", cv.as_string(), raw));
    }
    if let Some(v) = u8_at(data, 0x192c) {
        let s = match v as i64 {
            0 => "16:9".to_string(),
            1 => "4:3".to_string(),
            2 => "3:2".to_string(),
            3 => "1:1".to_string(),
            5 => "Panorama".to_string(),
            other => other.to_string(),
        };
        tags.push(mk("AspectRatio", s, Value::I32(v as i32)));
    }
    tags
}

fn tag2010g(data: &[u8], model: &str) -> Vec<Tag> {
    let mut tags = Vec::new();
    if let Some(v) = u32_at(data, 0x4) {
        let mut cv = Conv::Num(f64::from(v));
        if let Some(x) = conv_expr::eval("$val / 10", &cv) { cv = x; }
        let raw = Value::F64(cv.as_num());
        if let Some(x) = conv_expr::eval("sprintf(\"%.1f mm\",$val)", &cv) { cv = x; }
        tags.push(mk("WB_RGBLevels", cv.as_string(), raw));
    }
    if let Some(v) = u16_at(data, 0x32e) {
        let mut cv = Conv::Num(f64::from(v));
        if let Some(x) = conv_expr::eval("$val / 10", &cv) { cv = x; }
        let raw = Value::F64(cv.as_num());
        if let Some(x) = conv_expr::eval("sprintf(\"%.1f mm\",$val)", &cv) { cv = x; }
        tags.push(mk("MinFocalLength", cv.as_string(), raw));
    }
    if let Some(v) = u16_at(data, 0x330) {
        let mut cv = Conv::Num(f64::from(v));
        if let Some(x) = conv_expr::eval("$val / 10", &cv) { cv = x; }
        let raw = Value::F64(cv.as_num());
        if let Some(x) = conv_expr::eval("sprintf(\"%.1f mm\",$val)", &cv) { cv = x; }
        tags.push(mk("MaxFocalLength", cv.as_string(), raw));
    }
    if let Some(v) = u16_at(data, 0x344) {
        let mut cv = Conv::Num(f64::from(v));
        if let Some(x) = conv_expr::eval("100 * 2**(16 - $val/256)", &cv) { cv = x; }
        let raw = Value::F64(cv.as_num());
        if let Some(x) = conv_expr::eval("sprintf(\"%.0f\",$val)", &cv) { cv = x; }
        tags.push(mk("SonyISO", cv.as_string(), raw));
    }
    if !MODEL_RE_3.is_match(model) {
        if let Some(v) = u8_at(data, 0x18bd) {
            let s = match v as i64 {
                0 => "Unknown".to_string(),
                1 => "APS-C".to_string(),
                2 => "Full-frame".to_string(),
                other => other.to_string(),
            };
            tags.push(mk("LensFormat", s, Value::I32(v as i32)));
        }
    }
    if let Some(v) = u8_at(data, 0x18be) {
        let s = match v as i64 {
            0 => "Unknown".to_string(),
            1 => "A-mount".to_string(),
            2 => "E-mount".to_string(),
            other => other.to_string(),
        };
        tags.push(mk("LensMount", s, Value::I32(v as i32)));
    }
    if !MODEL_RE_3.is_match(model) {
        if let Some(v) = u8_at(data, 0x18c4) {
            tags.push(mk("DistortionCorrParamsPresent", v.to_string(), Value::I32(v as i32)));
        }
    }
    if !MODEL_RE_3.is_match(model) {
        if let Some(v) = u8_at(data, 0x18c5) {
            tags.push(mk("DistortionCorrParamsNumber", v.to_string(), Value::I32(v as i32)));
        }
    }
    if let Some(v) = u8_at(data, 0x1958) {
        let s = match v as i64 {
            0 => "16:9".to_string(),
            1 => "4:3".to_string(),
            2 => "3:2".to_string(),
            3 => "1:1".to_string(),
            5 => "Panorama".to_string(),
            other => other.to_string(),
        };
        tags.push(mk("AspectRatio", s, Value::I32(v as i32)));
    }
    tags
}

fn tag2010h(data: &[u8], model: &str) -> Vec<Tag> {
    let mut tags = Vec::new();
    if let Some(v) = u32_at(data, 0x4) {
        let mut cv = Conv::Num(f64::from(v));
        if let Some(x) = conv_expr::eval("$val / 10", &cv) { cv = x; }
        let raw = Value::F64(cv.as_num());
        if let Some(x) = conv_expr::eval("sprintf(\"%.1f mm\",$val)", &cv) { cv = x; }
        tags.push(mk("WB_RGBLevels", cv.as_string(), raw));
    }
    if let Some(v) = u16_at(data, 0x32e) {
        let mut cv = Conv::Num(f64::from(v));
        if let Some(x) = conv_expr::eval("$val / 10", &cv) { cv = x; }
        let raw = Value::F64(cv.as_num());
        if let Some(x) = conv_expr::eval("sprintf(\"%.1f mm\",$val)", &cv) { cv = x; }
        tags.push(mk("MinFocalLength", cv.as_string(), raw));
    }
    if let Some(v) = u16_at(data, 0x330) {
        let mut cv = Conv::Num(f64::from(v));
        if let Some(x) = conv_expr::eval("$val / 10", &cv) { cv = x; }
        let raw = Value::F64(cv.as_num());
        if let Some(x) = conv_expr::eval("sprintf(\"%.1f mm\",$val)", &cv) { cv = x; }
        tags.push(mk("MaxFocalLength", cv.as_string(), raw));
    }
    if let Some(v) = u16_at(data, 0x346) {
        let mut cv = Conv::Num(f64::from(v));
        if let Some(x) = conv_expr::eval("100 * 2**(16 - $val/256)", &cv) { cv = x; }
        let raw = Value::F64(cv.as_num());
        if let Some(x) = conv_expr::eval("sprintf(\"%.0f\",$val)", &cv) { cv = x; }
        tags.push(mk("SonyISO", cv.as_string(), raw));
    }
    if !MODEL_RE_3.is_match(model) {
        if let Some(v) = u8_at(data, 0x18ed) {
            let s = match v as i64 {
                0 => "Unknown".to_string(),
                1 => "APS-C".to_string(),
                2 => "Full-frame".to_string(),
                other => other.to_string(),
            };
            tags.push(mk("LensFormat", s, Value::I32(v as i32)));
        }
    }
    if let Some(v) = u8_at(data, 0x18ee) {
        let s = match v as i64 {
            0 => "Unknown".to_string(),
            1 => "A-mount".to_string(),
            2 => "E-mount".to_string(),
            other => other.to_string(),
        };
        tags.push(mk("LensMount", s, Value::I32(v as i32)));
    }
    if !MODEL_RE_3.is_match(model) {
        if let Some(v) = u8_at(data, 0x18f4) {
            tags.push(mk("DistortionCorrParamsPresent", v.to_string(), Value::I32(v as i32)));
        }
    }
    if !MODEL_RE_3.is_match(model) {
        if let Some(v) = u8_at(data, 0x18f5) {
            tags.push(mk("DistortionCorrParamsNumber", v.to_string(), Value::I32(v as i32)));
        }
    }
    if let Some(v) = u8_at(data, 0x192c) {
        let s = match v as i64 {
            0 => "16:9".to_string(),
            1 => "4:3".to_string(),
            2 => "3:2".to_string(),
            3 => "1:1".to_string(),
            5 => "Panorama".to_string(),
            other => other.to_string(),
        };
        tags.push(mk("AspectRatio", s, Value::I32(v as i32)));
    }
    tags
}

fn tag2010i(data: &[u8], model: &str) -> Vec<Tag> {
    let mut tags = Vec::new();
    if let Some(v) = u32_at(data, 0x4) {
        let mut cv = Conv::Num(f64::from(v));
        if let Some(x) = conv_expr::eval("$val / 10", &cv) { cv = x; }
        let raw = Value::F64(cv.as_num());
        if let Some(x) = conv_expr::eval("sprintf(\"%.1f mm\",$val)", &cv) { cv = x; }
        tags.push(mk("WB_RGBLevels", cv.as_string(), raw));
    }
    if let Some(v) = u16_at(data, 0x30c) {
        let mut cv = Conv::Num(f64::from(v));
        if let Some(x) = conv_expr::eval("$val / 10", &cv) { cv = x; }
        let raw = Value::F64(cv.as_num());
        if let Some(x) = conv_expr::eval("sprintf(\"%.1f mm\",$val)", &cv) { cv = x; }
        tags.push(mk("MinFocalLength", cv.as_string(), raw));
    }
    if let Some(v) = u16_at(data, 0x30e) {
        let mut cv = Conv::Num(f64::from(v));
        if let Some(x) = conv_expr::eval("$val / 10", &cv) { cv = x; }
        let raw = Value::F64(cv.as_num());
        if let Some(x) = conv_expr::eval("sprintf(\"%.1f mm\",$val)", &cv) { cv = x; }
        tags.push(mk("MaxFocalLength", cv.as_string(), raw));
    }
    if let Some(v) = u16_at(data, 0x320) {
        let mut cv = Conv::Num(f64::from(v));
        if let Some(x) = conv_expr::eval("100 * 2**(16 - $val/256)", &cv) { cv = x; }
        let raw = Value::F64(cv.as_num());
        if let Some(x) = conv_expr::eval("sprintf(\"%.0f\",$val)", &cv) { cv = x; }
        tags.push(mk("SonyISO", cv.as_string(), raw));
    }
    if !MODEL_RE_3.is_match(model) {
        if let Some(v) = u8_at(data, 0x17f1) {
            let s = match v as i64 {
                0 => "Unknown".to_string(),
                1 => "APS-C".to_string(),
                2 => "Full-frame".to_string(),
                other => other.to_string(),
            };
            tags.push(mk("LensFormat", s, Value::I32(v as i32)));
        }
    }
    if let Some(v) = u8_at(data, 0x17f2) {
        let s = match v as i64 {
            0 => "Unknown".to_string(),
            1 => "A-mount".to_string(),
            2 => "E-mount".to_string(),
            other => other.to_string(),
        };
        tags.push(mk("LensMount", s, Value::I32(v as i32)));
    }
    if !MODEL_RE_3.is_match(model) {
        if let Some(v) = u8_at(data, 0x17f8) {
            tags.push(mk("DistortionCorrParamsPresent", v.to_string(), Value::I32(v as i32)));
        }
    }
    if !MODEL_RE_3.is_match(model) {
        if let Some(v) = u8_at(data, 0x17f9) {
            tags.push(mk("DistortionCorrParamsNumber", v.to_string(), Value::I32(v as i32)));
        }
    }
    if let Some(v) = u8_at(data, 0x188c) {
        let s = match v as i64 {
            0 => "16:9".to_string(),
            1 => "4:3".to_string(),
            2 => "3:2".to_string(),
            3 => "1:1".to_string(),
            5 => "Panorama".to_string(),
            other => other.to_string(),
        };
        tags.push(mk("AspectRatio", s, Value::I32(v as i32)));
    }
    tags
}

fn tag9050a(data: &[u8], model: &str) -> Vec<Tag> {
    let mut tags = Vec::new();
    if !MODEL_RE_5.is_match(model) {
        if let Some(v) = u8_at(data, 0x0) {
            let mut cv = Conv::Num(f64::from(v));
            if let Some(x) = conv_expr::eval("2 ** (($val/8 - 1.06) / 2)", &cv) { cv = x; }
            let raw = Value::F64(cv.as_num());
            if let Some(x) = conv_expr::eval("sprintf(\"%.1f\",$val)", &cv) { cv = x; }
            tags.push(mk("SonyMaxAperture", cv.as_string(), raw));
        }
    }
    if !MODEL_RE_5.is_match(model) {
        if let Some(v) = u8_at(data, 0x1) {
            let mut cv = Conv::Num(f64::from(v));
            if let Some(x) = conv_expr::eval("2 ** (($val/8 - 1.06) / 2)", &cv) { cv = x; }
            let raw = Value::F64(cv.as_num());
            if let Some(x) = conv_expr::eval("sprintf(\"%.0f\",$val)", &cv) { cv = x; }
            tags.push(mk("SonyMinAperture", cv.as_string(), raw));
        }
    }
    if let Some(v) = u8_at(data, 0x31) {
        let s = match v as i64 {
            0 => "No Flash present".to_string(),
            2 => "Flash Inhibited".to_string(),
            64 => "Built-in Flash present".to_string(),
            65 => "Built-in Flash Fired".to_string(),
            66 => "Built-in Flash Inhibited".to_string(),
            128 => "External Flash present".to_string(),
            129 => "External Flash Fired".to_string(),
            other => other.to_string(),
        };
        tags.push(mk("FlashStatus", s, Value::I32(v as i32)));
    }
    if let Some(v) = u32_at(data, 0x32) {
        tags.push(mk("ShutterCount", v.to_string(), Value::I32(v as i32)));
    }
    if let Some(v) = u16_at(data, 0x3a) {
        let mut cv = Conv::Num(f64::from(v));
        if let Some(x) = conv_expr::eval("$val ? 2 ** (16 - $val/256) : 0", &cv) { cv = x; }
        let raw = Value::F64(cv.as_num());
        if let Some(x) = conv_expr::eval("$val ? Image::ExifTool::Exif::PrintExposureTime($val) : \"Bulb\"", &cv) { cv = x; }
        tags.push(mk("SonyExposureTime", cv.as_string(), raw));
    }
    if let Some(v) = u16_at(data, 0x3c) {
        let mut cv = Conv::Num(f64::from(v));
        if let Some(x) = conv_expr::eval("2 ** (($val/256 - 16) / 2)", &cv) { cv = x; }
        let raw = Value::F64(cv.as_num());
        if let Some(x) = conv_expr::eval("sprintf(\"%.1f\",$val)", &cv) { cv = x; }
        tags.push(mk("SonyFNumber", cv.as_string(), raw));
    }
    if let Some(v) = u8_at(data, 0x3f) {
        let s = match v as i64 {
            0 => "Normal".to_string(),
            1 => "Continuous".to_string(),
            2 => "Continuous - Exposure Bracketing".to_string(),
            3 => "DRO or White Balance Bracketing".to_string(),
            5 => "Continuous - Burst".to_string(),
            6 => "Single Frame - Capture During Movie".to_string(),
            7 => "Continuous - Sweep Panorama".to_string(),
            8 => "Continuous - Anti-Motion Blur, Hand-held Twilight".to_string(),
            9 => "Continuous - HDR".to_string(),
            10 => "Continuous - Background defocus".to_string(),
            13 => "Continuous - 3D Sweep Panorama".to_string(),
            15 => "Continuous - High Resolution Sweep Panorama".to_string(),
            16 => "Continuous - 3D Image".to_string(),
            17 => "Continuous - Burst 2".to_string(),
            18 => "Normal - iAuto+".to_string(),
            19 => "Continuous - Speed/Advance Priority".to_string(),
            20 => "Continuous - Multi Frame NR".to_string(),
            23 => "Single-frame - Exposure Bracketing".to_string(),
            26 => "Continuous Low".to_string(),
            27 => "Continuous - High Sensitivity".to_string(),
            28 => "Smile Shutter".to_string(),
            29 => "Continuous - Tele-zoom Advance Priority".to_string(),
            146 => "Single Frame - Movie Capture".to_string(),
            other => other.to_string(),
        };
        tags.push(mk("ReleaseMode2", s, Value::I32(v as i32)));
    }
    if !MODEL_RE_6.is_match(model) {
        if let Some(v) = u8_at(data, 0x67) {
            let s = match v as i64 {
                0 => "Normal".to_string(),
                1 => "Continuous".to_string(),
                2 => "Continuous - Exposure Bracketing".to_string(),
                3 => "DRO or White Balance Bracketing".to_string(),
                5 => "Continuous - Burst".to_string(),
                6 => "Single Frame - Capture During Movie".to_string(),
                7 => "Continuous - Sweep Panorama".to_string(),
                8 => "Continuous - Anti-Motion Blur, Hand-held Twilight".to_string(),
                9 => "Continuous - HDR".to_string(),
                10 => "Continuous - Background defocus".to_string(),
                13 => "Continuous - 3D Sweep Panorama".to_string(),
                15 => "Continuous - High Resolution Sweep Panorama".to_string(),
                16 => "Continuous - 3D Image".to_string(),
                17 => "Continuous - Burst 2".to_string(),
                18 => "Normal - iAuto+".to_string(),
                19 => "Continuous - Speed/Advance Priority".to_string(),
                20 => "Continuous - Multi Frame NR".to_string(),
                23 => "Single-frame - Exposure Bracketing".to_string(),
                26 => "Continuous Low".to_string(),
                27 => "Continuous - High Sensitivity".to_string(),
                28 => "Smile Shutter".to_string(),
                29 => "Continuous - Tele-zoom Advance Priority".to_string(),
                146 => "Single Frame - Movie Capture".to_string(),
                other => other.to_string(),
            };
            tags.push(mk("ReleaseMode2", s, Value::I32(v as i32)));
        }
    }
    if let Some(v) = u8_at(data, 0x105) {
        let s = match v as i64 {
            0 => "Unknown".to_string(),
            1 => "A-mount".to_string(),
            2 => "E-mount".to_string(),
            other => other.to_string(),
        };
        tags.push(mk("LensMount", s, Value::I32(v as i32)));
    }
    if let Some(v) = u8_at(data, 0x106) {
        let s = match v as i64 {
            0 => "Unknown".to_string(),
            1 => "APS-C".to_string(),
            2 => "Full-frame".to_string(),
            other => other.to_string(),
        };
        tags.push(mk("LensFormat", s, Value::I32(v as i32)));
    }
    if let Some(v) = u8_at(data, 0x10b) {
        tags.push(mk("DistortionCorrParamsPresent", v.to_string(), Value::I32(v as i32)));
    }
    if MODEL_RE_7.is_match(model) {
        if let Some(v) = u8_at(data, 0x114) {
            let s = match v as i64 {
                0 => "Off".to_string(),
                1 => "On".to_string(),
                other => other.to_string(),
            };
            tags.push(mk("APS-CSizeCapture", s, Value::I32(v as i32)));
        }
    }
    if MODEL_RE_8.is_match(model) {
        if let Some(v) = u32_at(data, 0x1a0) {
            tags.push(mk("ShutterCount3", v.to_string(), Value::I32(v as i32)));
        }
    }
    if MODEL_RE_9.is_match(model) {
        if let Some(v) = u32_at(data, 0x1aa) {
            tags.push(mk("ShutterCount3", v.to_string(), Value::I32(v as i32)));
        }
    }
    if MODEL_RE_10.is_match(model) {
        if let Some(v) = u32_at(data, 0x1bd) {
            tags.push(mk("ShutterCount3", v.to_string(), Value::I32(v as i32)));
        }
    }
    tags
}

fn tag9050b(data: &[u8], model: &str) -> Vec<Tag> {
    let mut tags = Vec::new();
    if MODEL_RE_11.is_match(model) {
        if let Some(v) = u8_at(data, 0x0) {
            let mut cv = Conv::Num(f64::from(v));
            if let Some(x) = conv_expr::eval("2 ** (($val/8 - 1.06) / 2)", &cv) { cv = x; }
            let raw = Value::F64(cv.as_num());
            if let Some(x) = conv_expr::eval("sprintf(\"%.1f\",$val)", &cv) { cv = x; }
            tags.push(mk("SonyMaxAperture", cv.as_string(), raw));
        }
    }
    if MODEL_RE_11.is_match(model) {
        if let Some(v) = u8_at(data, 0x1) {
            let mut cv = Conv::Num(f64::from(v));
            if let Some(x) = conv_expr::eval("2 ** (($val/8 - 1.06) / 2)", &cv) { cv = x; }
            let raw = Value::F64(cv.as_num());
            if let Some(x) = conv_expr::eval("sprintf(\"%.0f\",$val)", &cv) { cv = x; }
            tags.push(mk("SonyMinAperture", cv.as_string(), raw));
        }
    }
    if let Some(v) = u8_at(data, 0x39) {
        let s = match v as i64 {
            0 => "No Flash present".to_string(),
            2 => "Flash Inhibited".to_string(),
            64 => "Built-in Flash present".to_string(),
            65 => "Built-in Flash Fired".to_string(),
            66 => "Built-in Flash Inhibited".to_string(),
            128 => "External Flash present".to_string(),
            129 => "External Flash Fired".to_string(),
            131 => "External Flash ???".to_string(),
            other => other.to_string(),
        };
        tags.push(mk("FlashStatus", s, Value::I32(v as i32)));
    }
    if let Some(v) = u32_at(data, 0x3a) {
        tags.push(mk("ShutterCount", v.to_string(), Value::I32(v as i32)));
    }
    if let Some(v) = u16_at(data, 0x46) {
        let mut cv = Conv::Num(f64::from(v));
        if let Some(x) = conv_expr::eval("$val ? 2 ** (16 - $val/256) : 0", &cv) { cv = x; }
        let raw = Value::F64(cv.as_num());
        if let Some(x) = conv_expr::eval("$val ? Image::ExifTool::Exif::PrintExposureTime($val) : \"Bulb\"", &cv) { cv = x; }
        tags.push(mk("SonyExposureTime", cv.as_string(), raw));
    }
    if let Some(v) = u16_at(data, 0x48) {
        let mut cv = Conv::Num(f64::from(v));
        if let Some(x) = conv_expr::eval("2 ** (($val/256 - 16) / 2)", &cv) { cv = x; }
        let raw = Value::F64(cv.as_num());
        if let Some(x) = conv_expr::eval("sprintf(\"%.1f\",$val)", &cv) { cv = x; }
        tags.push(mk("SonyFNumber", cv.as_string(), raw));
    }
    if let Some(v) = u8_at(data, 0x4b) {
        let s = match v as i64 {
            0 => "Normal".to_string(),
            1 => "Continuous".to_string(),
            2 => "Continuous - Exposure Bracketing".to_string(),
            3 => "DRO or White Balance Bracketing".to_string(),
            5 => "Continuous - Burst".to_string(),
            6 => "Single Frame - Capture During Movie".to_string(),
            7 => "Continuous - Sweep Panorama".to_string(),
            8 => "Continuous - Anti-Motion Blur, Hand-held Twilight".to_string(),
            9 => "Continuous - HDR".to_string(),
            10 => "Continuous - Background defocus".to_string(),
            13 => "Continuous - 3D Sweep Panorama".to_string(),
            15 => "Continuous - High Resolution Sweep Panorama".to_string(),
            16 => "Continuous - 3D Image".to_string(),
            17 => "Continuous - Burst 2".to_string(),
            18 => "Normal - iAuto+".to_string(),
            19 => "Continuous - Speed/Advance Priority".to_string(),
            20 => "Continuous - Multi Frame NR".to_string(),
            23 => "Single-frame - Exposure Bracketing".to_string(),
            26 => "Continuous Low".to_string(),
            27 => "Continuous - High Sensitivity".to_string(),
            28 => "Smile Shutter".to_string(),
            29 => "Continuous - Tele-zoom Advance Priority".to_string(),
            146 => "Single Frame - Movie Capture".to_string(),
            other => other.to_string(),
        };
        tags.push(mk("ReleaseMode2", s, Value::I32(v as i32)));
    }
    if MODEL_RE_12.is_match(model) {
        if let Some(v) = u8_at(data, 0x6d) {
            let s = match v as i64 {
                0 => "Normal".to_string(),
                1 => "Continuous".to_string(),
                2 => "Continuous - Exposure Bracketing".to_string(),
                3 => "DRO or White Balance Bracketing".to_string(),
                5 => "Continuous - Burst".to_string(),
                6 => "Single Frame - Capture During Movie".to_string(),
                7 => "Continuous - Sweep Panorama".to_string(),
                8 => "Continuous - Anti-Motion Blur, Hand-held Twilight".to_string(),
                9 => "Continuous - HDR".to_string(),
                10 => "Continuous - Background defocus".to_string(),
                13 => "Continuous - 3D Sweep Panorama".to_string(),
                15 => "Continuous - High Resolution Sweep Panorama".to_string(),
                16 => "Continuous - 3D Image".to_string(),
                17 => "Continuous - Burst 2".to_string(),
                18 => "Normal - iAuto+".to_string(),
                19 => "Continuous - Speed/Advance Priority".to_string(),
                20 => "Continuous - Multi Frame NR".to_string(),
                23 => "Single-frame - Exposure Bracketing".to_string(),
                26 => "Continuous Low".to_string(),
                27 => "Continuous - High Sensitivity".to_string(),
                28 => "Smile Shutter".to_string(),
                29 => "Continuous - Tele-zoom Advance Priority".to_string(),
                146 => "Single Frame - Movie Capture".to_string(),
                other => other.to_string(),
            };
            tags.push(mk("ReleaseMode2", s, Value::I32(v as i32)));
        }
    }
    if let Some(v) = u8_at(data, 0x105) {
        let s = match v as i64 {
            0 => "Unknown".to_string(),
            1 => "A-mount".to_string(),
            2 => "E-mount".to_string(),
            other => other.to_string(),
        };
        tags.push(mk("LensMount", s, Value::I32(v as i32)));
    }
    if let Some(v) = u8_at(data, 0x106) {
        let s = match v as i64 {
            0 => "Unknown".to_string(),
            1 => "APS-C".to_string(),
            2 => "Full-frame".to_string(),
            other => other.to_string(),
        };
        tags.push(mk("LensFormat", s, Value::I32(v as i32)));
    }
    if let Some(v) = u8_at(data, 0x10b) {
        tags.push(mk("DistortionCorrParamsPresent", v.to_string(), Value::I32(v as i32)));
    }
    if MODEL_RE_13.is_match(model) {
        if let Some(v) = u8_at(data, 0x114) {
            let s = match v as i64 {
                0 => "Off".to_string(),
                1 => "On".to_string(),
                other => other.to_string(),
            };
            tags.push(mk("APS-CSizeCapture", s, Value::I32(v as i32)));
        }
    }
    if MODEL_RE_14.is_match(model) {
        if let Some(v) = u32_at(data, 0x19f) {
            tags.push(mk("ShutterCount3", v.to_string(), Value::I32(v as i32)));
        }
    }
    if MODEL_RE_15.is_match(model) {
        if let Some(v) = u32_at(data, 0x1cb) {
            tags.push(mk("ShutterCount3", v.to_string(), Value::I32(v as i32)));
        }
    }
    if MODEL_RE_16.is_match(model) {
        if let Some(v) = u32_at(data, 0x1cd) {
            tags.push(mk("ShutterCount3", v.to_string(), Value::I32(v as i32)));
        }
    }
    if MODEL_RE_15.is_match(model) {
        if let Some(v) = u8_at(data, 0x21a) {
            let s = match v as i64 {
                0 => "Off".to_string(),
                1 => "On".to_string(),
                other => other.to_string(),
            };
            tags.push(mk("APS-CSizeCapture", s, Value::I32(v as i32)));
        }
    }
    tags
}

fn tag9050c(data: &[u8], model: &str) -> Vec<Tag> {
    let _ = model;
    let mut tags = Vec::new();
    if let Some(v) = u8_at(data, 0x39) {
        let s = match v as i64 {
            0 => "No Flash present".to_string(),
            2 => "Flash Inhibited".to_string(),
            64 => "Built-in Flash present".to_string(),
            65 => "Built-in Flash Fired".to_string(),
            66 => "Built-in Flash Inhibited".to_string(),
            128 => "External Flash present".to_string(),
            129 => "External Flash Fired".to_string(),
            other => other.to_string(),
        };
        tags.push(mk("FlashStatus", s, Value::I32(v as i32)));
    }
    if let Some(v) = u32_at(data, 0x3a) {
        tags.push(mk("ShutterCount", v.to_string(), Value::I32(v as i32)));
    }
    if let Some(v) = u16_at(data, 0x46) {
        let mut cv = Conv::Num(f64::from(v));
        if let Some(x) = conv_expr::eval("$val ? 2 ** (16 - $val/256) : 0", &cv) { cv = x; }
        let raw = Value::F64(cv.as_num());
        if let Some(x) = conv_expr::eval("$val ? Image::ExifTool::Exif::PrintExposureTime($val) : \"Bulb\"", &cv) { cv = x; }
        tags.push(mk("SonyExposureTime", cv.as_string(), raw));
    }
    if let Some(v) = u16_at(data, 0x48) {
        let mut cv = Conv::Num(f64::from(v));
        if let Some(x) = conv_expr::eval("2 ** (($val/256 - 16) / 2)", &cv) { cv = x; }
        let raw = Value::F64(cv.as_num());
        if let Some(x) = conv_expr::eval("sprintf(\"%.1f\",$val)", &cv) { cv = x; }
        tags.push(mk("SonyFNumber", cv.as_string(), raw));
    }
    if let Some(v) = u8_at(data, 0x4b) {
        let s = match v as i64 {
            0 => "Normal".to_string(),
            1 => "Continuous".to_string(),
            2 => "Continuous - Exposure Bracketing".to_string(),
            3 => "DRO or White Balance Bracketing".to_string(),
            5 => "Continuous - Burst".to_string(),
            6 => "Single Frame - Capture During Movie".to_string(),
            7 => "Continuous - Sweep Panorama".to_string(),
            8 => "Continuous - Anti-Motion Blur, Hand-held Twilight".to_string(),
            9 => "Continuous - HDR".to_string(),
            10 => "Continuous - Background defocus".to_string(),
            13 => "Continuous - 3D Sweep Panorama".to_string(),
            15 => "Continuous - High Resolution Sweep Panorama".to_string(),
            16 => "Continuous - 3D Image".to_string(),
            17 => "Continuous - Burst 2".to_string(),
            18 => "Normal - iAuto+".to_string(),
            19 => "Continuous - Speed/Advance Priority".to_string(),
            20 => "Continuous - Multi Frame NR".to_string(),
            23 => "Single-frame - Exposure Bracketing".to_string(),
            26 => "Continuous Low".to_string(),
            27 => "Continuous - High Sensitivity".to_string(),
            28 => "Smile Shutter".to_string(),
            29 => "Continuous - Tele-zoom Advance Priority".to_string(),
            146 => "Single Frame - Movie Capture".to_string(),
            other => other.to_string(),
        };
        tags.push(mk("ReleaseMode2", s, Value::I32(v as i32)));
    }
    if let Some(v) = u16_at(data, 0x66) {
        let mut cv = Conv::Num(f64::from(v));
        if let Some(x) = conv_expr::eval("$val ? 2 ** (16 - $val/256) : 0", &cv) { cv = x; }
        let raw = Value::F64(cv.as_num());
        if let Some(x) = conv_expr::eval("$val ? Image::ExifTool::Exif::PrintExposureTime($val) : \"Bulb\"", &cv) { cv = x; }
        tags.push(mk("SonyExposureTime", cv.as_string(), raw));
    }
    if let Some(v) = u16_at(data, 0x68) {
        let mut cv = Conv::Num(f64::from(v));
        if let Some(x) = conv_expr::eval("2 ** (($val/256 - 16) / 2)", &cv) { cv = x; }
        let raw = Value::F64(cv.as_num());
        if let Some(x) = conv_expr::eval("sprintf(\"%.1f\",$val)", &cv) { cv = x; }
        tags.push(mk("SonyFNumber", cv.as_string(), raw));
    }
    if let Some(v) = u8_at(data, 0x6b) {
        let s = match v as i64 {
            0 => "Normal".to_string(),
            1 => "Continuous".to_string(),
            2 => "Continuous - Exposure Bracketing".to_string(),
            3 => "DRO or White Balance Bracketing".to_string(),
            5 => "Continuous - Burst".to_string(),
            6 => "Single Frame - Capture During Movie".to_string(),
            7 => "Continuous - Sweep Panorama".to_string(),
            8 => "Continuous - Anti-Motion Blur, Hand-held Twilight".to_string(),
            9 => "Continuous - HDR".to_string(),
            10 => "Continuous - Background defocus".to_string(),
            13 => "Continuous - 3D Sweep Panorama".to_string(),
            15 => "Continuous - High Resolution Sweep Panorama".to_string(),
            16 => "Continuous - 3D Image".to_string(),
            17 => "Continuous - Burst 2".to_string(),
            18 => "Normal - iAuto+".to_string(),
            19 => "Continuous - Speed/Advance Priority".to_string(),
            20 => "Continuous - Multi Frame NR".to_string(),
            23 => "Single-frame - Exposure Bracketing".to_string(),
            26 => "Continuous Low".to_string(),
            27 => "Continuous - High Sensitivity".to_string(),
            28 => "Smile Shutter".to_string(),
            29 => "Continuous - Tele-zoom Advance Priority".to_string(),
            146 => "Single Frame - Movie Capture".to_string(),
            other => other.to_string(),
        };
        tags.push(mk("ReleaseMode2", s, Value::I32(v as i32)));
    }
    tags
}

fn tag9050d(data: &[u8], model: &str) -> Vec<Tag> {
    let mut tags = Vec::new();
    if MODEL_RE_17.is_match(model) {
        if let Some(v) = u32_at(data, 0xa) {
            tags.push(mk("ShutterCount", v.to_string(), Value::I32(v as i32)));
        }
    }
    if let Some(v) = u16_at(data, 0x1a) {
        let mut cv = Conv::Num(f64::from(v));
        if let Some(x) = conv_expr::eval("$val ? 2 ** (16 - $val/256) : 0", &cv) { cv = x; }
        let raw = Value::F64(cv.as_num());
        if let Some(x) = conv_expr::eval("$val ? Image::ExifTool::Exif::PrintExposureTime($val) : \"Bulb\"", &cv) { cv = x; }
        tags.push(mk("SonyExposureTime", cv.as_string(), raw));
    }
    if !MODEL_RE_18.is_match(model) {
        if let Some(v) = u16_at(data, 0x1c) {
            let mut cv = Conv::Num(f64::from(v));
            if let Some(x) = conv_expr::eval("2 ** (($val/256 - 16) / 2)", &cv) { cv = x; }
            let raw = Value::F64(cv.as_num());
            if let Some(x) = conv_expr::eval("sprintf(\"%.1f\",$val)", &cv) { cv = x; }
            tags.push(mk("SonyFNumber", cv.as_string(), raw));
        }
    }
    if let Some(v) = u8_at(data, 0x1f) {
        let s = match v as i64 {
            0 => "Normal".to_string(),
            1 => "Continuous".to_string(),
            2 => "Continuous - Exposure Bracketing".to_string(),
            3 => "DRO or White Balance Bracketing".to_string(),
            5 => "Continuous - Burst".to_string(),
            6 => "Single Frame - Capture During Movie".to_string(),
            7 => "Continuous - Sweep Panorama".to_string(),
            8 => "Continuous - Anti-Motion Blur, Hand-held Twilight".to_string(),
            9 => "Continuous - HDR".to_string(),
            10 => "Continuous - Background defocus".to_string(),
            13 => "Continuous - 3D Sweep Panorama".to_string(),
            15 => "Continuous - High Resolution Sweep Panorama".to_string(),
            16 => "Continuous - 3D Image".to_string(),
            17 => "Continuous - Burst 2".to_string(),
            18 => "Normal - iAuto+".to_string(),
            19 => "Continuous - Speed/Advance Priority".to_string(),
            20 => "Continuous - Multi Frame NR".to_string(),
            23 => "Single-frame - Exposure Bracketing".to_string(),
            26 => "Continuous Low".to_string(),
            27 => "Continuous - High Sensitivity".to_string(),
            28 => "Smile Shutter".to_string(),
            29 => "Continuous - Tele-zoom Advance Priority".to_string(),
            146 => "Single Frame - Movie Capture".to_string(),
            other => other.to_string(),
        };
        tags.push(mk("ReleaseMode2", s, Value::I32(v as i32)));
    }
    tags
}

fn tag9400a(data: &[u8], model: &str) -> Vec<Tag> {
    let mut tags = Vec::new();
    if !MODEL_RE_19.is_match(model) {
        if let Some(v) = u8_at(data, 0x8) {
            let s = match v as i64 {
                0 => "No".to_string(),
                1 => "Yes".to_string(),
                other => other.to_string(),
            };
            tags.push(mk("DigitalZoom", s, Value::I32(v as i32)));
        }
    }
    if let Some(v) = u32_at(data, 0x1a) {
        tags.push(mk("ShotNumberSincePowerUp", v.to_string(), Value::I32(v as i32)));
    }
    if let Some(v) = u8_at(data, 0x22) {
        let s = match v as i64 {
            0 => "Continuous".to_string(),
            1 => "1 shot".to_string(),
            2 => "2 shots".to_string(),
            3 => "3 shots".to_string(),
            4 => "4 shots".to_string(),
            5 => "5 shots".to_string(),
            6 => "6 shots".to_string(),
            10 => "10 shots".to_string(),
            100 => "Continuous - iSweep Panorama".to_string(),
            200 => "Continuous - Sweep Panorama".to_string(),
            other => other.to_string(),
        };
        tags.push(mk("SequenceLength", s, Value::I32(v as i32)));
    }
    if let Some(v) = u8_at(data, 0x28) {
        let s = match v as i64 {
            1 => "Horizontal (normal)".to_string(),
            3 => "Rotate 180".to_string(),
            6 => "Rotate 90 CW".to_string(),
            8 => "Rotate 270 CW".to_string(),
            other => other.to_string(),
        };
        tags.push(mk("CameraOrientation", s, Value::I32(v as i32)));
    }
    if let Some(v) = u8_at(data, 0x29) {
        let s = match v as i64 {
            0 => "JPEG".to_string(),
            1 => "RAW".to_string(),
            2 => "RAW + JPEG".to_string(),
            3 => "JPEG + MPO".to_string(),
            other => other.to_string(),
        };
        tags.push(mk("Quality2", s, Value::I32(v as i32)));
    }
    if MODEL_RE_20.is_match(model) {
        if let Some(v) = u16_at(data, 0x44) {
            let mut cv = Conv::Num(f64::from(v));
            let raw = Value::F64(cv.as_num());
            if let Some(x) = conv_expr::eval("$val > 0 ? 8*$val : \"n.a.\"", &cv) { cv = x; }
            tags.push(mk("SonyImageHeight", cv.as_string(), raw));
        }
    }
    if MODEL_RE_20.is_match(model) {
        if let Some(v) = u8_at(data, 0x52) {
            let mut cv = Conv::Num(f64::from(v));
            let raw = Value::F64(cv.as_num());
            if let Some(x) = conv_expr::eval("sprintf(\"20%.2d\", $val)", &cv) { cv = x; }
            tags.push(mk("ModelReleaseYear", cv.as_string(), raw));
        }
    }
    tags
}

fn tag9400b(data: &[u8], model: &str) -> Vec<Tag> {
    let _ = model;
    let mut tags = Vec::new();
    if let Some(v) = u8_at(data, 0x8) {
        let s = match v as i64 {
            0 => "No".to_string(),
            1 => "Yes".to_string(),
            other => other.to_string(),
        };
        tags.push(mk("DigitalZoom", s, Value::I32(v as i32)));
    }
    if let Some(v) = u32_at(data, 0x16) {
        tags.push(mk("ShotNumberSincePowerUp", v.to_string(), Value::I32(v as i32)));
    }
    if let Some(v) = u8_at(data, 0x1e) {
        let s = match v as i64 {
            0 => "Continuous".to_string(),
            1 => "1 shot".to_string(),
            2 => "2 shots".to_string(),
            3 => "3 shots".to_string(),
            4 => "4 shots".to_string(),
            5 => "5 shots".to_string(),
            6 => "6 shots".to_string(),
            10 => "10 shots".to_string(),
            100 => "Continuous - iSweep Panorama".to_string(),
            200 => "Continuous - Sweep Panorama".to_string(),
            other => other.to_string(),
        };
        tags.push(mk("SequenceLength", s, Value::I32(v as i32)));
    }
    if let Some(v) = u8_at(data, 0x24) {
        let s = match v as i64 {
            1 => "Horizontal (normal)".to_string(),
            3 => "Rotate 180".to_string(),
            6 => "Rotate 90 CW".to_string(),
            8 => "Rotate 270 CW".to_string(),
            other => other.to_string(),
        };
        tags.push(mk("CameraOrientation", s, Value::I32(v as i32)));
    }
    if let Some(v) = u8_at(data, 0x25) {
        let s = match v as i64 {
            0 => "JPEG".to_string(),
            1 => "RAW".to_string(),
            2 => "RAW + JPEG".to_string(),
            3 => "JPEG + MPO".to_string(),
            other => other.to_string(),
        };
        tags.push(mk("Quality2", s, Value::I32(v as i32)));
    }
    if let Some(v) = u16_at(data, 0x3f) {
        let mut cv = Conv::Num(f64::from(v));
        let raw = Value::F64(cv.as_num());
        if let Some(x) = conv_expr::eval("$val > 0 ? 8*$val : \"n.a.\"", &cv) { cv = x; }
        tags.push(mk("SonyImageHeight", cv.as_string(), raw));
    }
    if let Some(v) = u8_at(data, 0x46) {
        let mut cv = Conv::Num(f64::from(v));
        let raw = Value::F64(cv.as_num());
        if let Some(x) = conv_expr::eval("sprintf(\"20%.2d\", $val)", &cv) { cv = x; }
        tags.push(mk("ModelReleaseYear", cv.as_string(), raw));
    }
    tags
}

fn tag9400c(data: &[u8], model: &str) -> Vec<Tag> {
    let mut tags = Vec::new();
    if MODEL_RE_21.is_match(model) {
        if let Some(v) = u32_at(data, 0x9) {
            tags.push(mk("ShotNumberSincePowerUp", v.to_string(), Value::I32(v as i32)));
        }
    }
    if let Some(v) = u8_at(data, 0x12) {
        let s = match v as i64 {
            0 => "Continuous".to_string(),
            1 => "1 shot".to_string(),
            2 => "2 shots".to_string(),
            3 => "3 shots".to_string(),
            4 => "4 shots".to_string(),
            5 => "5 shots".to_string(),
            6 => "6 shots".to_string(),
            7 => "7 shots".to_string(),
            9 => "9 shots".to_string(),
            10 => "10 shots".to_string(),
            12 => "12 shots".to_string(),
            16 => "16 shots".to_string(),
            100 => "Continuous - iSweep Panorama".to_string(),
            200 => "Continuous - Sweep Panorama".to_string(),
            other => other.to_string(),
        };
        tags.push(mk("SequenceLength", s, Value::I32(v as i32)));
    }
    if let Some(v) = u8_at(data, 0x1a) {
        let s = match v as i64 {
            0 => "Continuous".to_string(),
            1 => "1 file".to_string(),
            2 => "2 files".to_string(),
            3 => "3 files".to_string(),
            5 => "5 files".to_string(),
            7 => "7 files".to_string(),
            9 => "9 files".to_string(),
            10 => "10 files".to_string(),
            other => other.to_string(),
        };
        tags.push(mk("SequenceLength", s, Value::I32(v as i32)));
    }
    if let Some(v) = u8_at(data, 0x29) {
        let s = match v as i64 {
            1 => "Horizontal (normal)".to_string(),
            3 => "Rotate 180".to_string(),
            6 => "Rotate 90 CW".to_string(),
            8 => "Rotate 270 CW".to_string(),
            other => other.to_string(),
        };
        tags.push(mk("CameraOrientation", s, Value::I32(v as i32)));
    }
    if !MODEL_RE_22.is_match(model) {
        if let Some(v) = u8_at(data, 0x53) {
            let mut cv = Conv::Num(f64::from(v));
            let raw = Value::F64(cv.as_num());
            if let Some(x) = conv_expr::eval("sprintf(\"20%.2d\", $val)", &cv) { cv = x; }
            tags.push(mk("ModelReleaseYear", cv.as_string(), raw));
        }
    }
    if MODEL_RE_23.is_match(model) {
        if let Some(v) = u8_at(data, 0x133) {
            let s = match v as i64 {
                7 => "Electronic".to_string(),
                23 => "Mechanical".to_string(),
                other => other.to_string(),
            };
            tags.push(mk("ShutterType", s, Value::I32(v as i32)));
        }
    }
    if MODEL_RE_24.is_match(model) {
        if let Some(v) = u8_at(data, 0x139) {
            let s = match v as i64 {
                7 => "Electronic".to_string(),
                23 => "Mechanical".to_string(),
                other => other.to_string(),
            };
            tags.push(mk("ShutterType", s, Value::I32(v as i32)));
        }
    }
    if MODEL_RE_25.is_match(model) {
        if let Some(v) = u8_at(data, 0x13f) {
            let s = match v as i64 {
                7 => "Electronic".to_string(),
                23 => "Mechanical".to_string(),
                other => other.to_string(),
            };
            tags.push(mk("ShutterType", s, Value::I32(v as i32)));
        }
    }
    tags
}

fn tag9402(data: &[u8], model: &str) -> Vec<Tag> {
    let mut tags = Vec::new();
    if let Some(v) = u8_at(data, 0x2) {
        tags.push(mk("TempTest1", v.to_string(), Value::I32(v as i32)));
    }
    if let Some(v) = u8_at(data, 0x16) {
        let s = match v as i64 {
            0 => "Manual".to_string(),
            2 => "AF-S".to_string(),
            3 => "AF-C".to_string(),
            4 => "AF-A".to_string(),
            6 => "DMF".to_string(),
            7 => "AF-D".to_string(),
            other => other.to_string(),
        };
        tags.push(mk("FocusMode", s, Value::I32(v as i32)));
    }
    if let Some(v) = u8_at(data, 0x17) {
        let s = match v as i64 {
            0 => "Multi".to_string(),
            1 => "Center".to_string(),
            2 => "Spot".to_string(),
            3 => "Flexible Spot".to_string(),
            10 => "Selective (for Miniature effect)".to_string(),
            11 => "Zone".to_string(),
            12 => "Expanded Flexible Spot".to_string(),
            13 => "Custom AF Area".to_string(),
            14 => "Tracking".to_string(),
            15 => "Face Tracking".to_string(),
            20 => "Animal Eye Tracking".to_string(),
            21 => "Human Eye Tracking".to_string(),
            22 => "Object Tracking???".to_string(),
            255 => "Manual".to_string(),
            other => other.to_string(),
        };
        tags.push(mk("AFAreaMode", s, Value::I32(v as i32)));
    }
    if !MODEL_RE_2.is_match(model) {
        if let Some(v) = u8_at(data, 0x2d) {
            tags.push(mk("FocusPosition2", v.to_string(), Value::I32(v as i32)));
        }
    }
    tags
}

fn tag9403(data: &[u8], model: &str) -> Vec<Tag> {
    let _ = model;
    let mut tags = Vec::new();
    if let Some(v) = u8_at(data, 0x4) {
        tags.push(mk("TempTest2", v.to_string(), Value::I32(v as i32)));
    }
    tags
}

fn tag9404a(data: &[u8], model: &str) -> Vec<Tag> {
    let mut tags = Vec::new();
    if !MODEL_RE_26.is_match(model) {
        if let Some(v) = u16_at(data, 0xb) {
            let mut cv = Conv::Num(f64::from(v));
            let raw = Value::F64(cv.as_num());
            if let Some(x) = conv_expr::eval("sprintf(\"%.0f%%\",$val/10.24)", &cv) { cv = x; }
            tags.push(mk("IntelligentAuto", cv.as_string(), raw));
        }
    }
    tags
}

fn tag9404b(data: &[u8], model: &str) -> Vec<Tag> {
    let mut tags = Vec::new();
    if !MODEL_RE_27.is_match(model) {
        if let Some(v) = u16_at(data, 0xc) {
            let mut cv = Conv::Num(f64::from(v));
            let raw = Value::F64(cv.as_num());
            if let Some(x) = conv_expr::eval("sprintf(\"%.0f%%\",$val/10.24)", &cv) { cv = x; }
            tags.push(mk("IntelligentAuto", cv.as_string(), raw));
        }
    }
    if MODEL_RE_27.is_match(model) {
        if let Some(v) = u8_at(data, 0x20) {
            tags.push(mk("FocusPosition2", v.to_string(), Value::I32(v as i32)));
        }
    }
    tags
}

fn tag9405a(data: &[u8], model: &str) -> Vec<Tag> {
    let mut tags = Vec::new();
    if !MODEL_RE_2.is_match(model) {
        if let Some(v) = u8_at(data, 0x600) {
            tags.push(mk("DistortionCorrParamsPresent", v.to_string(), Value::I32(v as i32)));
        }
    }
    if let Some(v) = u8_at(data, 0x601) {
        let s = match v as i64 {
            0 => "None".to_string(),
            1 => "Applied".to_string(),
            other => other.to_string(),
        };
        tags.push(mk("DistortionCorrection", s, Value::I32(v as i32)));
    }
    if !MODEL_RE_2.is_match(model) {
        if let Some(v) = u8_at(data, 0x603) {
            let s = match v as i64 {
                0 => "Unknown".to_string(),
                1 => "APS-C".to_string(),
                2 => "Full-frame".to_string(),
                other => other.to_string(),
            };
            tags.push(mk("LensFormat", s, Value::I32(v as i32)));
        }
    }
    if let Some(v) = u8_at(data, 0x604) {
        let s = match v as i64 {
            0 => "Unknown".to_string(),
            1 => "A-mount".to_string(),
            2 => "E-mount".to_string(),
            other => other.to_string(),
        };
        tags.push(mk("LensMount", s, Value::I32(v as i32)));
    }
    tags
}

fn tag9405b(data: &[u8], model: &str) -> Vec<Tag> {
    let mut tags = Vec::new();
    if let Some(v) = u16_at(data, 0x4) {
        let mut cv = Conv::Num(f64::from(v));
        if let Some(x) = conv_expr::eval("100 * 2**(16 - $val/256)", &cv) { cv = x; }
        let raw = Value::F64(cv.as_num());
        if let Some(x) = conv_expr::eval("sprintf(\"%.0f\",$val)", &cv) { cv = x; }
        tags.push(mk("SonyISO", cv.as_string(), raw));
    }
    if let Some(v) = u16_at(data, 0x6) {
        let mut cv = Conv::Num(f64::from(v));
        if let Some(x) = conv_expr::eval("100 * 2**(16 - $val/256)", &cv) { cv = x; }
        let raw = Value::F64(cv.as_num());
        if let Some(x) = conv_expr::eval("sprintf(\"%.0f\",$val)", &cv) { cv = x; }
        tags.push(mk("BaseISO", cv.as_string(), raw));
    }
    if let Some(v) = u16_at(data, 0xa) {
        let mut cv = Conv::Num(f64::from(v));
        if let Some(x) = conv_expr::eval("$val ? 2 ** (16 - $val/256) : 0", &cv) { cv = x; }
        let raw = Value::F64(cv.as_num());
        if let Some(x) = conv_expr::eval("$val ? Image::ExifTool::Exif::PrintExposureTime($val) : \"Bulb\"", &cv) { cv = x; }
        tags.push(mk("SonyExposureTime2", cv.as_string(), raw));
    }
    if !MODEL_RE_28.is_match(model) {
        if let Some(v) = u16_at(data, 0x14) {
            let mut cv = Conv::Num(f64::from(v));
            if let Some(x) = conv_expr::eval("2 ** (($val/256 - 16) / 2)", &cv) { cv = x; }
            let raw = Value::F64(cv.as_num());
            if let Some(x) = conv_expr::eval("sprintf(\"%.1f\",$val)", &cv) { cv = x; }
            tags.push(mk("SonyFNumber", cv.as_string(), raw));
        }
    }
    if let Some(v) = u16_at(data, 0x16) {
        let mut cv = Conv::Num(f64::from(v));
        if let Some(x) = conv_expr::eval("2 ** (($val/256 - 16) / 2)", &cv) { cv = x; }
        let raw = Value::F64(cv.as_num());
        if let Some(x) = conv_expr::eval("sprintf(\"%.1f\",$val)", &cv) { cv = x; }
        tags.push(mk("SonyMaxApertureValue", cv.as_string(), raw));
    }
    if let Some(v) = u16_at(data, 0x24) {
        let s = match v as i64 {
            0 => "Off".to_string(),
            1 => "Low".to_string(),
            2 => "Normal".to_string(),
            3 => "High".to_string(),
            other => other.to_string(),
        };
        tags.push(mk("SonyImageWidthMax", s, Value::I32(v as i32)));
    }
    if let Some(v) = u8_at(data, 0x44) {
        let s = match v as i64 {
            0 => "Off".to_string(),
            1 => "On".to_string(),
            other => other.to_string(),
        };
        tags.push(mk("LongExposureNoiseReduction", s, Value::I32(v as i32)));
    }
    if let Some(v) = u8_at(data, 0x46) {
        let s = match v as i64 {
            0 => "Standard".to_string(),
            1 => "Vivid".to_string(),
            2 => "Neutral".to_string(),
            3 => "Portrait".to_string(),
            4 => "Landscape".to_string(),
            5 => "B&W".to_string(),
            6 => "Clear".to_string(),
            7 => "Deep".to_string(),
            8 => "Light".to_string(),
            9 => "Sunset".to_string(),
            10 => "Night View/Portrait".to_string(),
            11 => "Autumn Leaves".to_string(),
            13 => "Sepia".to_string(),
            15 => "FL".to_string(),
            16 => "VV2".to_string(),
            17 => "IN".to_string(),
            18 => "SH".to_string(),
            255 => "Off".to_string(),
            other => other.to_string(),
        };
        tags.push(mk("CreativeStyle", s, Value::I32(v as i32)));
    }
    if let Some(v) = i8_at(data, 0x52) {
        let mut cv = Conv::Num(f64::from(v));
        let raw = Value::F64(cv.as_num());
        if let Some(x) = conv_expr::eval("$val > 0 ? \"+$val\" : $val", &cv) { cv = x; }
        tags.push(mk("Sharpness", cv.as_string(), raw));
    }
    if !MODEL_RE_3.is_match(model) {
        if let Some(v) = u8_at(data, 0x5a) {
            tags.push(mk("DistortionCorrParamsPresent", v.to_string(), Value::I32(v as i32)));
        }
    }
    if let Some(v) = u8_at(data, 0x5b) {
        let s = match v as i64 {
            0 => "None".to_string(),
            1 => "Applied".to_string(),
            other => other.to_string(),
        };
        tags.push(mk("DistortionCorrection", s, Value::I32(v as i32)));
    }
    if !MODEL_RE_3.is_match(model) {
        if let Some(v) = u8_at(data, 0x5d) {
            let s = match v as i64 {
                0 => "Unknown".to_string(),
                1 => "APS-C".to_string(),
                2 => "Full-frame".to_string(),
                other => other.to_string(),
            };
            tags.push(mk("LensFormat", s, Value::I32(v as i32)));
        }
    }
    if let Some(v) = u8_at(data, 0x5e) {
        let s = match v as i64 {
            0 => "Unknown".to_string(),
            1 => "A-mount".to_string(),
            2 => "E-mount".to_string(),
            other => other.to_string(),
        };
        tags.push(mk("LensMount", s, Value::I32(v as i32)));
    }
    if !MODEL_RE_29.is_match(model) {
        if let Some(v) = u16_at(data, 0x342) {
            let mut cv = Conv::Num(f64::from(v));
            let raw = Value::F64(cv.as_num());
            if let Some(x) = conv_expr::eval("sprintf(\"%.0f%%\",$val/10.24)", &cv) { cv = x; }
            tags.push(mk("LensZoomPosition", cv.as_string(), raw));
        }
    }
    if MODEL_RE_30.is_match(model) {
        if let Some(v) = u16_at(data, 0x34e) {
            let mut cv = Conv::Num(f64::from(v));
            let raw = Value::F64(cv.as_num());
            if let Some(x) = conv_expr::eval("sprintf(\"%.0f%%\",$val/10.24)", &cv) { cv = x; }
            tags.push(mk("LensZoomPosition", cv.as_string(), raw));
        }
    }
    if MODEL_RE_31.is_match(model) {
        if let Some(v) = u16_at(data, 0x35a) {
            let mut cv = Conv::Num(f64::from(v));
            let raw = Value::F64(cv.as_num());
            if let Some(x) = conv_expr::eval("sprintf(\"%.0f%%\",$val/10.24)", &cv) { cv = x; }
            tags.push(mk("LensZoomPosition", cv.as_string(), raw));
        }
    }
    tags
}

fn tag9406(data: &[u8], model: &str) -> Vec<Tag> {
    let mut tags = Vec::new();
    if let Some(v) = u8_at(data, 0x5) {
        let mut cv = Conv::Num(f64::from(v));
        if let Some(x) = conv_expr::eval("($val - 32) / 1.8", &cv) { cv = x; }
        let raw = Value::F64(cv.as_num());
        if let Some(x) = conv_expr::eval("sprintf(\"%.1f C\",$val)", &cv) { cv = x; }
        tags.push(mk("BatteryTemperature", cv.as_string(), raw));
    }
    if let Some(v) = u8_at(data, 0x6) {
        let mut cv = Conv::Num(f64::from(v));
        let raw = Value::F64(cv.as_num());
        if let Some(x) = conv_expr::eval("\"$val%\"", &cv) { cv = x; }
        tags.push(mk("BatteryLevelGrip1", cv.as_string(), raw));
    }
    if let Some(v) = u8_at(data, 0x7) {
        let mut cv = Conv::Num(f64::from(v));
        let raw = Value::F64(cv.as_num());
        if let Some(x) = conv_expr::eval("\"$val%\"", &cv) { cv = x; }
        tags.push(mk("BatteryLevel", cv.as_string(), raw));
    }
    if !MODEL_RE_32.is_match(model) {
        if let Some(v) = u8_at(data, 0x8) {
            let mut cv = Conv::Num(f64::from(v));
            let raw = Value::F64(cv.as_num());
            if let Some(x) = conv_expr::eval("\"$val%\"", &cv) { cv = x; }
            tags.push(mk("BatteryLevelGrip2", cv.as_string(), raw));
        }
    }
    tags
}

fn tag9406b(data: &[u8], model: &str) -> Vec<Tag> {
    let _ = model;
    let mut tags = Vec::new();
    if let Some(v) = u8_at(data, 0x1) {
        tags.push(mk("Battery2", v.to_string(), Value::I32(v as i32)));
    }
    if let Some(v) = u8_at(data, 0x4) {
        tags.push(mk("BatteryStatus1", v.to_string(), Value::I32(v as i32)));
    }
    tags
}

fn tag940a(data: &[u8], model: &str) -> Vec<Tag> {
    let _ = model;
    let mut tags = Vec::new();
    if let Some(v) = u32_at(data, 0x4) {
        let s = match v as i64 {
            0 => "Center".to_string(),
            1 => "Top".to_string(),
            2 => "Upper-right".to_string(),
            3 => "Right".to_string(),
            4 => "Lower-right".to_string(),
            5 => "Bottom".to_string(),
            6 => "Lower-left".to_string(),
            7 => "Left".to_string(),
            8 => "Upper-left".to_string(),
            9 => "Far Right".to_string(),
            10 => "Far Left".to_string(),
            11 => "Upper-middle".to_string(),
            12 => "Near Right".to_string(),
            13 => "Lower-middle".to_string(),
            14 => "Near Left".to_string(),
            15 => "Upper Far Right".to_string(),
            16 => "Lower Far Right".to_string(),
            17 => "Lower Far Left".to_string(),
            18 => "Upper Far Left".to_string(),
            30721 => "Center Zone".to_string(),
            98844 => "Right Zone".to_string(),
            262143 => "(all LA-EA4)".to_string(),
            394688 => "Left Zone".to_string(),
            2147483647 => "(all)".to_string(),
            4294967295 => "n/a".to_string(),
            other => other.to_string(),
        };
        tags.push(mk("AFPointsSelected", s, Value::I32(v as i32)));
    }
    tags
}

fn tag940c(data: &[u8], model: &str) -> Vec<Tag> {
    let _ = model;
    let mut tags = Vec::new();
    if let Some(v) = u8_at(data, 0x8) {
        let s = match v as i64 {
            0 => "Unknown".to_string(),
            1 => "A-mount (1)".to_string(),
            4 => "E-mount".to_string(),
            5 => "A-mount (5)".to_string(),
            other => other.to_string(),
        };
        tags.push(mk("LensMount2", s, Value::I32(v as i32)));
    }
    if let Some(v) = u16_at(data, 0x9) {
        tags.push(mk("LensType3", v.to_string(), Value::I32(v as i32)));
    }
    if let Some(v) = u16_at(data, 0xb) {
        let mut cv = Conv::Num(f64::from(v));
        let raw = Value::F64(cv.as_num());
        if let Some(x) = conv_expr::eval("sprintf(\"%x.%.2x\",$val>>8,$val&0xff)", &cv) { cv = x; }
        tags.push(mk("CameraE-mountVersion", cv.as_string(), raw));
    }
    tags
}

fn tag9416(data: &[u8], model: &str) -> Vec<Tag> {
    let mut tags = Vec::new();
    if let Some(v) = u8_at(data, 0x0) {
        let mut cv = Conv::Num(f64::from(v));
        let raw = Value::F64(cv.as_num());
        if let Some(x) = conv_expr::eval("sprintf(\"%3d\",$val)", &cv) { cv = x; }
        tags.push(mk("Tag9416_0000", cv.as_string(), raw));
    }
    if let Some(v) = u16_at(data, 0x4) {
        let mut cv = Conv::Num(f64::from(v));
        if let Some(x) = conv_expr::eval("100 * 2**(16 - $val/256)", &cv) { cv = x; }
        let raw = Value::F64(cv.as_num());
        if let Some(x) = conv_expr::eval("sprintf(\"%.0f\",$val)", &cv) { cv = x; }
        tags.push(mk("SonyISO", cv.as_string(), raw));
    }
    if let Some(v) = u16_at(data, 0x6) {
        let mut cv = Conv::Num(f64::from(v));
        if let Some(x) = conv_expr::eval("$val ? 2 ** (16 - $val/256) : 0", &cv) { cv = x; }
        let raw = Value::F64(cv.as_num());
        if let Some(x) = conv_expr::eval("$val ? Image::ExifTool::Exif::PrintExposureTime($val) : \"Bulb\"", &cv) { cv = x; }
        tags.push(mk("SonyExposureTime2", cv.as_string(), raw));
    }
    if let Some(v) = u16_at(data, 0x10) {
        let mut cv = Conv::Num(f64::from(v));
        if let Some(x) = conv_expr::eval("2 ** (($val/256 - 16) / 2)", &cv) { cv = x; }
        let raw = Value::F64(cv.as_num());
        if let Some(x) = conv_expr::eval("sprintf(\"%.1f\",$val)", &cv) { cv = x; }
        tags.push(mk("SonyFNumber2", cv.as_string(), raw));
    }
    if let Some(v) = u16_at(data, 0x12) {
        let mut cv = Conv::Num(f64::from(v));
        if let Some(x) = conv_expr::eval("2 ** (($val/256 - 16) / 2)", &cv) { cv = x; }
        let raw = Value::F64(cv.as_num());
        if let Some(x) = conv_expr::eval("sprintf(\"%.1f\",$val)", &cv) { cv = x; }
        tags.push(mk("SonyMaxApertureValue", cv.as_string(), raw));
    }
    if let Some(v) = u8_at(data, 0x35) {
        tags.push(mk("ExposureProgram", v.to_string(), Value::I32(v as i32)));
    }
    if let Some(v) = u8_at(data, 0x37) {
        let s = match v as i64 {
            0 => "Standard".to_string(),
            1 => "Vivid".to_string(),
            2 => "Neutral".to_string(),
            3 => "Portrait".to_string(),
            4 => "Landscape".to_string(),
            5 => "B&W".to_string(),
            6 => "Clear".to_string(),
            7 => "Deep".to_string(),
            8 => "Light".to_string(),
            9 => "Sunset".to_string(),
            10 => "Night View/Portrait".to_string(),
            11 => "Autumn Leaves".to_string(),
            13 => "Sepia".to_string(),
            15 => "FL".to_string(),
            16 => "VV2".to_string(),
            17 => "IN".to_string(),
            18 => "SH".to_string(),
            19 => "FL2".to_string(),
            20 => "FL3".to_string(),
            255 => "Off".to_string(),
            other => other.to_string(),
        };
        tags.push(mk("CreativeStyle", s, Value::I32(v as i32)));
    }
    if !MODEL_RE_33.is_match(model) {
        if let Some(v) = u8_at(data, 0x48) {
            let s = match v as i64 {
                0 => "Unknown".to_string(),
                1 => "A-mount".to_string(),
                2 => "E-mount".to_string(),
                3 => "A-mount (3)".to_string(),
                other => other.to_string(),
            };
            tags.push(mk("LensMount", s, Value::I32(v as i32)));
        }
    }
    if !MODEL_RE_33.is_match(model) {
        if let Some(v) = u8_at(data, 0x49) {
            let s = match v as i64 {
                0 => "Unknown".to_string(),
                1 => "APS-C".to_string(),
                2 => "Full-frame".to_string(),
                other => other.to_string(),
            };
            tags.push(mk("LensFormat", s, Value::I32(v as i32)));
        }
    }
    if let Some(v) = u8_at(data, 0x4a) {
        let s = match v as i64 {
            0 => "Unknown".to_string(),
            1 => "A-mount".to_string(),
            2 => "E-mount".to_string(),
            other => other.to_string(),
        };
        tags.push(mk("LensMount", s, Value::I32(v as i32)));
    }
    if let Some(v) = u16_at(data, 0x70) {
        let mut cv = Conv::Num(f64::from(v));
        if let Some(x) = conv_expr::eval("$val / 10", &cv) { cv = x; }
        let raw = Value::F64(cv.as_num());
        if let Some(x) = conv_expr::eval("sprintf(\"%.1f mm\",$val)", &cv) { cv = x; }
        tags.push(mk("FocalLength", cv.as_string(), raw));
    }
    if let Some(v) = u16_at(data, 0x73) {
        let mut cv = Conv::Num(f64::from(v));
        if let Some(x) = conv_expr::eval("$val / 10", &cv) { cv = x; }
        let raw = Value::F64(cv.as_num());
        if let Some(x) = conv_expr::eval("sprintf(\"%.1f mm\",$val)", &cv) { cv = x; }
        tags.push(mk("MinFocalLength", cv.as_string(), raw));
    }
    if let Some(v) = u16_at(data, 0x75) {
        let mut cv = Conv::Num(f64::from(v));
        if let Some(x) = conv_expr::eval("$val / 10", &cv) { cv = x; }
        let raw = Value::F64(cv.as_num());
        if let Some(x) = conv_expr::eval("sprintf(\"%.1f mm\",$val)", &cv) { cv = x; }
        tags.push(mk("MaxFocalLength", cv.as_string(), raw));
    }
    if MODEL_RE_34.is_match(model) {
        if let Some(v) = u8_at(data, 0x74a) {
            let s = match v as i64 {
                0 => "Off".to_string(),
                1 => "On".to_string(),
                other => other.to_string(),
            };
            tags.push(mk("APS-CSizeCapture", s, Value::I32(v as i32)));
        }
    }
    if MODEL_RE_35.is_match(model) {
        if let Some(v) = u8_at(data, 0x74f) {
            let s = match v as i64 {
                0 => "Off".to_string(),
                1 => "On".to_string(),
                other => other.to_string(),
            };
            tags.push(mk("APS-CSizeCapture", s, Value::I32(v as i32)));
        }
    }
    if MODEL_RE_36.is_match(model) {
        if let Some(v) = u8_at(data, 0x8b5) {
            let s = match v as i64 {
                0 => "Off".to_string(),
                1 => "On".to_string(),
                other => other.to_string(),
            };
            tags.push(mk("APS-CSizeCapture", s, Value::I32(v as i32)));
        }
    }
    if MODEL_RE_37.is_match(model) {
        if let Some(v) = u8_at(data, 0x8b7) {
            let s = match v as i64 {
                0 => "Off".to_string(),
                1 => "On".to_string(),
                other => other.to_string(),
            };
            tags.push(mk("APS-CSizeCapture", s, Value::I32(v as i32)));
        }
    }
    if MODEL_RE_38.is_match(model) {
        if let Some(v) = u8_at(data, 0x8e5) {
            let s = match v as i64 {
                0 => "Off".to_string(),
                1 => "On".to_string(),
                other => other.to_string(),
            };
            tags.push(mk("APS-CSizeCapture", s, Value::I32(v as i32)));
        }
    }
    tags
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Every generated pattern must compile: a bad one would otherwise
    /// only surface as a panic on whichever file first reaches it.
    #[test]
    fn every_model_pattern_compiles() {
        LazyLock::force(&MODEL_RE_0);
        LazyLock::force(&MODEL_RE_1);
        LazyLock::force(&MODEL_RE_2);
        LazyLock::force(&MODEL_RE_3);
        LazyLock::force(&MODEL_RE_4);
        LazyLock::force(&MODEL_RE_5);
        LazyLock::force(&MODEL_RE_6);
        LazyLock::force(&MODEL_RE_7);
        LazyLock::force(&MODEL_RE_8);
        LazyLock::force(&MODEL_RE_9);
        LazyLock::force(&MODEL_RE_10);
        LazyLock::force(&MODEL_RE_11);
        LazyLock::force(&MODEL_RE_12);
        LazyLock::force(&MODEL_RE_13);
        LazyLock::force(&MODEL_RE_14);
        LazyLock::force(&MODEL_RE_15);
        LazyLock::force(&MODEL_RE_16);
        LazyLock::force(&MODEL_RE_17);
        LazyLock::force(&MODEL_RE_18);
        LazyLock::force(&MODEL_RE_19);
        LazyLock::force(&MODEL_RE_20);
        LazyLock::force(&MODEL_RE_21);
        LazyLock::force(&MODEL_RE_22);
        LazyLock::force(&MODEL_RE_23);
        LazyLock::force(&MODEL_RE_24);
        LazyLock::force(&MODEL_RE_25);
        LazyLock::force(&MODEL_RE_26);
        LazyLock::force(&MODEL_RE_27);
        LazyLock::force(&MODEL_RE_28);
        LazyLock::force(&MODEL_RE_29);
        LazyLock::force(&MODEL_RE_30);
        LazyLock::force(&MODEL_RE_31);
        LazyLock::force(&MODEL_RE_32);
        LazyLock::force(&MODEL_RE_33);
        LazyLock::force(&MODEL_RE_34);
        LazyLock::force(&MODEL_RE_35);
        LazyLock::force(&MODEL_RE_36);
        LazyLock::force(&MODEL_RE_37);
        LazyLock::force(&MODEL_RE_38);
        LazyLock::force(&MODEL_RE_39);
        LazyLock::force(&MODEL_RE_40);
        LazyLock::force(&MODEL_RE_41);
        LazyLock::force(&MODEL_RE_42);
        LazyLock::force(&MODEL_RE_43);
        LazyLock::force(&MODEL_RE_44);
        LazyLock::force(&MODEL_RE_45);
        LazyLock::force(&MODEL_RE_46);
        LazyLock::force(&MODEL_RE_47);
        LazyLock::force(&MODEL_RE_48);
        LazyLock::force(&MODEL_RE_49);
    }
}
