#!/usr/bin/perl
# Generate src/tags/makernote_conv_generated.rs: the ValueConv and PrintConv
# EXPRESSIONS on the MakerNote Main tables.
#
# The hash-shaped conversions are already ported by gen_print_conv.pl. The ones
# written as Perl -- `$val ? ($val==0xffffffff ? "n/a" : $val) : "Auto"` --
# were not ported at all, so those tags printed their raw value. They are
# carried over verbatim here and evaluated by tags::conv_expr, which declines
# anything outside its grammar and leaves the raw value untouched.
#
# Anything this cannot express is named on stderr. Usage:
#   perl scripts/gen_makernote_conv.pl /path/to/exiftool > src/tags/makernote_conv_generated.rs

use strict;
use warnings;
no strict 'refs';

my $dir = $ARGV[0] || '/home/sylvain/dev/exiftool';
die "Cannot find $dir/lib\n" unless -d "$dir/lib";
unshift @INC, "$dir/lib";
require Image::ExifTool;

# The MakerNote Main tables our reader looks tags up in by numeric id.
# GoPro and Leica have no `Main` of their own in ExifTool -- GoPro's tags live
# in GPMF and its siblings, Leica's in Panasonic.pm -- so they are not listed.
my @MAKERS = qw(Sony Canon Nikon Olympus Panasonic Pentax FujiFilm Casio Ricoh
                Sigma Samsung Sanyo Minolta Apple DJI);

my (@rows, @skipped);
for my $maker (@MAKERS) {
    my $tbl = eval { Image::ExifTool::GetTagTable("Image::ExifTool::${maker}::Main") } or next;
    for my $id (Image::ExifTool::TagTableKeys($tbl)) {
        next unless $id =~ /^\d+$/;
        next if $id > 0xffff;
        my @infos = Image::ExifTool::GetTagInfoList($tbl, $id);
        # A conditioned chain can give one id several conversions; only an id
        # with a single entry is unambiguous from a numeric lookup.
        if (@infos > 1) {
            my %seen;
            for my $ti (@infos) {
                next unless ref $ti eq 'HASH';
                for my $k ('ValueConv', 'PrintConv') {
                    my $c = $$ti{$k};
                    $seen{"$k:$c"} = 1 if defined $c and not ref $c;
                }
            }
            if (keys %seen > 1) {
                push @skipped, sprintf("%s 0x%04x: %d conditioned entries disagree on their conversions",
                                       $maker, $id, scalar @infos);
                next;
            }
        }
        for my $ti (@infos) {
            next unless ref $ti eq 'HASH';
            my $name = $$ti{Name} // next;
            for my $kind ('ValueConv', 'PrintConv') {
                my $c = $$ti{$kind};
                next unless defined $c and not ref $c;   # a hash or code ref is not ours
                # A conversion that spans lines is still one expression.
                $c =~ s/\s+/ /g;
                $c =~ s/^ | $//g;
                next unless length $c;
                push @rows, [$maker, $id, $kind, $name, $c];
            }
            last;
        }
    }
}

my $ver = $Image::ExifTool::VERSION;
print <<"HEADER";
// \@generated by scripts/gen_makernote_conv.pl from ExifTool $ver. DO NOT EDIT.
//
// The ValueConv and PrintConv expressions on the MakerNote Main tables, carried
// over verbatim. `tags::conv_expr` evaluates them and declines anything outside
// its grammar, which leaves the raw value -- the same answer a reader that knew
// nothing of the conversion would give.

HEADER

for my $kind ('ValueConv', 'PrintConv') {
    my $fn = $kind eq 'ValueConv' ? 'value_conv' : 'print_conv';
    printf "/// The %s expression ExifTool applies to a MakerNote Main tag.\n", $kind;
    print  "#[must_use]\n";
    printf "pub fn %s_expr(maker: &str, tag: u16) -> Option<&'static str> {\n", $fn;
    print  "    Some(match (maker, tag) {\n";
    my %emitted;
    for my $r (sort { $a->[0] cmp $b->[0] or $a->[1] <=> $b->[1] } grep { $_->[2] eq $kind } @rows) {
        my ($maker, $id, undef, $name, $expr) = @$r;
        next if $emitted{"$maker/$id"}++;
        my $e = $expr;
        $e =~ s/\\/\\\\/g;
        $e =~ s/"/\\"/g;
        printf "        (\"%s\", %#06x) => \"%s\", // %s\n", $maker, $id, $e, $name;
    }
    print  "        _ => return None,\n    })\n}\n\n";
}

printf STDERR "%d expression(s) over %d makers\n", scalar @rows, scalar @MAKERS;
if (@skipped) {
    printf STDERR "\n%d id(s) NOT emitted:\n", scalar @skipped;
    print STDERR "  $_\n" for @skipped;
}
