#!/usr/bin/perl
# Generate the family-2 (category) lookup tables from ExifTool itself.
#
# ExifTool derives family 2 from each tag's `Groups => { 2 => '...' }`, falling
# back to the containing table's `GROUPS` default. Rather than re-parse the
# ~200 `Image::ExifTool::*` modules by hand, we ask ExifTool to do it: `-listx`
# dumps every table with its `g0`/`g1`/`g2` defaults and every tag with the
# families it overrides. That output is ExifTool's own resolution of the
# fallback chain, so it is authoritative by construction and follows upstream
# across releases.
#
# The same tag NAME can legitimately carry different categories in different
# tables (`BitsPerSample` is Image in one place and Audio in another), so the
# result is emitted as three tiers of decreasing specificity, keyed on the
# families we already assign:
#
#   FAMILY2_BY_G0_G1_NAME   "<g0>\x01<g1>\x01<name>"
#   FAMILY2_BY_G0_NAME      "<g0>\x01<name>"
#   FAMILY2_BY_NAME         "<name>"
#
# Each entry stores the *set* of categories ExifTool uses for that key, not a
# single winner: an ambiguous key lets the caller keep whatever the parser
# already decided (see `crate::tags::group2::family2_for`), because the parser
# knows which table the tag actually came from and a name lookup does not.
#
# A tier entry is omitted when its category set is identical to the one the next
# (less specific) tier would return, which is the common case — that prunes
# ~50000 redundant rows down to ~25000 meaningful ones.
#
# Usage (from the crate root):
#   perl scripts/gen_group2.pl [path/to/exiftool/dir] > src/tags/group2_generated.rs
#
# Default Perl ExifTool location: /home/sylvain/dev/exiftool.

use strict;
use warnings;

my $exiftool_dir = $ARGV[0] || '/home/sylvain/dev/exiftool';
die "Perl ExifTool not found at $exiftool_dir/exiftool\n"
    unless -f "$exiftool_dir/exiftool";

my $xml = `cd '$exiftool_dir' && perl exiftool -listx 2>/dev/null`;
die "exiftool -listx produced no output\n" unless length $xml;

my ($version) = $xml =~ /Generated by Image::ExifTool (\S+)/;
$version = '?' unless defined $version;

# ── Collect (g0, g1, name) => { category => 1 } ─────────────────────────────
my (%k3, %k2, %k1);
my ($tg0, $tg1, $tg2) = ('', '', '');
for my $line (split /\n/, $xml) {
    if ($line =~ /^<table name=/) {
        ($tg0) = $line =~ /g0='([^']*)'/;
        ($tg1) = $line =~ /g1='([^']*)'/;
        ($tg2) = $line =~ /g2='([^']*)'/;
        $_ = defined($_) ? $_ : '' for ($tg0, $tg1, $tg2);
        next;
    }
    next unless $line =~ /^\s*<tag id=.*? name='([A-Za-z0-9_\-]+)'/;
    my $name = $1;
    my ($g0, $g1, $g2) = ($tg0, $tg1, $tg2);
    $g0 = $1 if $line =~ /g0='([^']*)'/;
    $g1 = $1 if $line =~ /g1='([^']*)'/;
    $g2 = $1 if $line =~ /g2='([^']*)'/;
    # The pseudo-tag ForceWrite has "*" for every family: it belongs to no group.
    next if grep { !length($_) || $_ eq '*' } ($g0, $g1, $g2);

    $k3{"$g0\x01$g1\x01$name"}{$g2} = 1;
    $k2{"$g0\x01$name"}{$g2} = 1;
    $k1{$name}{$g2} = 1;
}

sub set_key { my $h = shift; return $h ? join(',', sort keys %$h) : '' }

# ── Prune tiers that add nothing over the next fallback ─────────────────────
my %keep2;
for my $key (sort keys %k2) {
    my (undef, $name) = split /\x01/, $key;
    $keep2{$key} = 1 if set_key($k2{$key}) ne set_key($k1{$name});
}
my %keep3;
for my $key (sort keys %k3) {
    my ($g0, undef, $name) = split /\x01/, $key;
    my $fallback = $keep2{"$g0\x01$name"} ? set_key($k2{"$g0\x01$name"}) : set_key($k1{$name});
    $keep3{$key} = 1 if set_key($k3{$key}) ne $fallback;
}

# ── Emit ────────────────────────────────────────────────────────────────────
print <<"HEADER";
//! Auto-generated family-2 (category) lookup tables, from ExifTool $version.
//!
//! Generated by `scripts/gen_group2.pl`. DO NOT EDIT MANUALLY.
//!
//! Three tiers of decreasing specificity, each sorted by key so the lookup in
//! [`super::group2`] can binary-search them. A key maps to every category
//! ExifTool assigns to it; more than one means the category depends on which
//! table the tag came from.

/// `(key, categories)`, sorted by key.
pub type Family2Entry = (&'static str, &'static [&'static str]);
HEADER

sub emit {
    my ($var, $doc, $map, $keep) = @_;
    my @keys = sort grep { !$keep || $keep->{$_} } keys %$map;
    printf "\n/// %s (%d entries).\npub static %s: &[Family2Entry] = &[\n", $doc, scalar @keys, $var;
    for my $key (@keys) {
        my $rust_key = $key;
        $rust_key =~ s/\x01/\\u{1}/g;
        my $cats = join ', ', map { "\"$_\"" } sort keys %{ $map->{$key} };
        print "    (\"$rust_key\", &[$cats]),\n";
    }
    print "];\n";
}

emit('FAMILY2_BY_G0_G1_NAME', 'Keyed on `"<family0>\\u{1}<family1>\\u{1}<name>"`', \%k3, \%keep3);
emit('FAMILY2_BY_G0_NAME',    'Keyed on `"<family0>\\u{1}<name>"`',                \%k2, \%keep2);
emit('FAMILY2_BY_NAME',       'Keyed on `"<name>"`',                               \%k1, undef);
