#!/usr/bin/perl
# Generate the set of XMP properties ExifTool stores at priority 0.
#
# `FoundTag` (ExifTool.pm:9469-9472) resolves a tag's priority in three steps:
#
#     my $priority = $$tagInfo{Priority};
#     unless (defined $priority) {
#         $priority = $$tbl{PRIORITY};
#         $priority = 0 if not defined $priority and $$tagInfo{Avoid};
#     }
#
# so `Avoid => 1` demotes a tag to priority 0 whenever neither the tag nor its
# table states a priority of its own. A priority-0 duplicate never displaces a
# stored value (the stored one is promoted to 1 first), which is how ExifTool
# keeps `IPTC:TimeCreated` even though `XMP-photomech:TimeCreated` is found
# later in the file.
#
# XMP is the one family where a name lookup is safe: its family-1 group is the
# namespace, so `(XMP-photomech, TimeCreated)` names exactly one tagInfo. A
# check over every table confirms it — no `(XMP-*, name)` pair carries priority
# 0 in one table and a higher priority in another. EXIF and QuickTime are
# deliberately left out: `IFD0` and `UserData` do collide that way, and Exif.pm's
# own `Priority => 0` entries are handled separately, against the PRIORITY_DIR.
#
# Usage: perl scripts/gen_priority0.pl ../exiftool > src/tags/priority0_generated.rs

use strict;
use warnings;

my $dir = shift or die "usage: $0 <path-to-exiftool-checkout>\n";
unshift @INC, "$dir/lib";
require Image::ExifTool;

Image::ExifTool::LoadAllTables();
my $all = \%Image::ExifTool::allTables; ## no critic

my %seen;
foreach my $tableName (sort keys %$all) {
    my $table = Image::ExifTool::GetTagTable($tableName);
    next unless ($$table{GROUPS}{0} // '') eq 'XMP';
    my $tablePriority = $$table{PRIORITY};
    foreach my $id (Image::ExifTool::TagTableKeys($table)) {
        foreach my $tagInfo (Image::ExifTool::GetTagInfoList($table, $id)) {
            next unless ref $tagInfo eq 'HASH';
            next if $$tagInfo{SubDirectory} and not defined $$tagInfo{Writable};
            my $priority = $$tagInfo{Priority};
            unless (defined $priority) {
                $priority = $tablePriority;
                $priority = 0 if not defined $priority and $$tagInfo{Avoid};
            }
            next unless defined $priority and $priority == 0;
            my $group1 = $$table{GROUPS}{1}
                // ($$tagInfo{Groups} ? $$tagInfo{Groups}{1} : undef)
                // next;
            next unless $group1 =~ /^XMP-/;
            $seen{"$group1\t$$tagInfo{Name}"} = 1;
        }
    }
}

my @entries = sort keys %seen;

print <<"HEADER";
//! AUTO-GENERATED by `scripts/gen_priority0.pl` — do not edit.
//!
//! XMP properties ExifTool stores at priority 0, so that finding one never
//! displaces a value already stored under the same tag name. Almost all of them
//! get there through `Avoid => 1`, which `FoundTag` (ExifTool.pm:9472) turns
//! into a priority of 0 when neither the tag nor its table sets one; the rest
//! come from the `PRIORITY => 0` mirror tables (XMP-exif, XMP-tiff, XMP-exifEX).
//!
//! Keyed on `(family 1, tag name)`, which is unambiguous for XMP: family 1 is
//! the namespace, so the pair names exactly one tagInfo.

/// `(family1, name)` pairs, sorted for binary search.
static XMP_PRIORITY0: &[(&str, &str)] = &[
HEADER

foreach my $entry (@entries) {
    my ($group1, $name) = split /\t/, $entry;
    print qq{    ("$group1", "$name"),\n};
}

print <<'FOOTER';
];

/// Whether ExifTool stores the XMP property `name` of namespace group `family1`
/// at priority 0.
pub fn xmp_is_priority0(family1: &str, name: &str) -> bool {
    XMP_PRIORITY0
        .binary_search_by(|&(g, n)| g.cmp(family1).then_with(|| n.cmp(name)))
        .is_ok()
}
FOOTER
