#!/usr/bin/perl
# Generate src/formats/font_charset.rs from ExifTool's Charset tables.
# This is a MECHANICAL, exact port of the Image::ExifTool::Charset::* hashes.
# Nothing is invented: each Rust entry mirrors one Perl hash entry.
#
# Two callers: Font.pm's TrueType 'name' table (see %ttCharset), and the
# conversion evaluator, whose `$self->Decode($val, "Latin")` and
# `$self->Decode($val, "MacRoman")` name these same sets.
#
# Usage: perl scripts/gen_font_charset.pl /path/to/exiftool/lib > src/formats/font_charset.rs
use strict;
use warnings;

my $lib = shift or die "usage: gen_font_charset.pl <exiftool-lib-dir>\n";
unshift @INC, $lib;

# csType 0x800/0x883 = variable-width (may have 2-byte lead hashes);
# 0x101 = single-byte fixed-width. Both decode with the same byte-walk here.
my @charsets = qw(MacRoman MacHebrew MacJapanese MacKorean MacChineseCN MacChineseTW
                  Latin Latin2);

my $SENTINEL = 0xFFFF; # value marker for a multi-code-point mapping

print <<'HEADER';
// @generated by scripts/gen_font_charset.pl from ExifTool's
// Image::ExifTool::Charset::Mac* tables. DO NOT EDIT BY HAND.
//
// A faithful port of the Mac 'name'-table character sets selected by
// Font.pm's %ttCharset, plus the sets `$self->Decode(...)` names. Decoding
// follows Charset.pm::Decompose: a byte-walk
// where a "lead" byte consumes the following byte to form a 2-byte code, an
// unmapped byte passes through unchanged, and a mapping may expand to several
// code points. Values are all <= 0xFFE6 so 0xFFFF is a safe multi-CP sentinel.
#![allow(clippy::all)]

pub struct MacCharset {
    /// Lead bytes (those with a 2-byte sub-table), sorted ascending.
    pub lead: &'static [u8],
    /// Single-byte keys (sorted) and their single-code-point values.
    pub s_keys: &'static [u8],
    pub s_vals: &'static [u16],
    /// Double-byte keys `(lead << 8 | trail)` (sorted) and single-CP values.
    pub d_keys: &'static [u16],
    pub d_vals: &'static [u16],
    /// Keys (single-byte < 0x100, or `lead<<8|trail`) whose value is several
    /// code points; referenced when the parallel value array holds 0xFFFF.
    pub multi: &'static [(u16, &'static [u16])],
}

const SENTINEL: u16 = 0xFFFF;

impl MacCharset {
    /// Decode `bytes` into a UTF-8 `String`, mirroring Charset.pm::Decompose
    /// for a variable-width Mac character set.
    pub fn decode(&self, bytes: &[u8]) -> String {
        let mut out = String::new();
        let mut i = 0usize;
        while i < bytes.len() {
            let b = bytes[i];
            i += 1;
            if self.lead.binary_search(&b).is_ok() {
                if i < bytes.len() {
                    let key = ((b as u16) << 8) | bytes[i] as u16;
                    if let Ok(idx) = self.d_keys.binary_search(&key) {
                        i += 1;
                        self.push_val(&mut out, key, self.d_vals[idx]);
                    } else {
                        // Encoding error: '?' and DO NOT consume the trail byte.
                        out.push('?');
                    }
                } else {
                    out.push('?');
                }
            } else if let Ok(idx) = self.s_keys.binary_search(&b) {
                self.push_val(&mut out, b as u16, self.s_vals[idx]);
            } else {
                // No translation: pass the byte through unchanged.
                out.push(b as char);
            }
        }
        out
    }

    fn push_val(&self, out: &mut String, key: u16, val: u16) {
        if val != SENTINEL {
            if let Some(c) = char::from_u32(val as u32) {
                out.push(c);
            }
            return;
        }
        if let Ok(idx) = self.multi.binary_search_by_key(&key, |e| e.0) {
            for &cp in self.multi[idx].1 {
                if let Some(c) = char::from_u32(cp as u32) {
                    out.push(c);
                }
            }
        }
    }
}
HEADER

for my $cs (@charsets) {
    my $mod = "Image/ExifTool/Charset/$cs.pm";
    require $mod;
    no strict 'refs';
    my $h = \%{"Image::ExifTool::Charset::$cs"};

    my (%single, %double, %lead, @multi);
    my $flat = sub {
        my $v = shift;
        return ref $v eq 'ARRAY' ? [@$v] : [$v];
    };
    for my $lb (sort { $a <=> $b } keys %$h) {
        my $v = $h->{$lb};
        if (ref $v eq 'HASH') {
            $lead{$lb} = 1;
            for my $tb (sort { $a <=> $b } keys %$v) {
                my $cps = $flat->($v->{$tb});
                my $key = ($lb << 8) | $tb;
                if (@$cps == 1) {
                    $double{$key} = $cps->[0];
                } else {
                    $double{$key} = $SENTINEL;
                    push @multi, [$key, $cps];
                }
            }
        } else {
            my $cps = $flat->($v);
            if (@$cps == 1) {
                $single{$lb} = $cps->[0];
            } else {
                $single{$lb} = $SENTINEL;
                push @multi, [$lb, $cps];
            }
        }
    }

    my @lead = sort { $a <=> $b } keys %lead;
    my @sk = sort { $a <=> $b } keys %single;
    my @dk = sort { $a <=> $b } keys %double;
    @multi = sort { $a->[0] <=> $b->[0] } @multi;

    my $fmt_list = sub {
        my ($ref, $w) = @_;
        my $s = join(', ', map { sprintf($w, $_) } @$ref);
        return $s;
    };

    print "\n#[rustfmt::skip]\npub static ${\ uc $cs }: MacCharset = MacCharset {\n";
    print "    lead: &[", $fmt_list->(\@lead, '0x%02x'), "],\n";
    print "    s_keys: &[", $fmt_list->(\@sk, '0x%02x'), "],\n";
    print "    s_vals: &[", $fmt_list->([map { $single{$_} } @sk], '0x%04x'), "],\n";
    print "    d_keys: &[", $fmt_list->(\@dk, '0x%04x'), "],\n";
    print "    d_vals: &[", $fmt_list->([map { $double{$_} } @dk], '0x%04x'), "],\n";
    print "    multi: &[";
    print join(', ', map {
        my ($k, $cps) = @$_;
        sprintf('(0x%04x, &[%s])', $k, join(', ', map { sprintf('0x%04x', $_) } @$cps));
    } @multi);
    print "],\n";
    print "};\n";
}
