#!/usr/bin/perl
# Generate src/tags/conv_tables_generated.rs: the plain lookup hashes that
# ExifTool's named conversion functions read, ported one entry at a time.
#
# These are data, not code -- %genre in ID3.pm, %minoltaWhiteBalance in
# Minolta.pm -- but PrintGenre and ConvertWhiteBalance are useless without
# them, so they belong beside the evaluator that calls those functions.
#
# Anything this script cannot express is named on stderr and counted. It never
# drops an entry silently.
#
# Usage: perl scripts/gen_conv_tables.pl /path/to/exiftool/lib > src/tags/conv_tables_generated.rs

use strict;
use warnings;

my $lib = $ARGV[0] || '../exiftool/lib';
die "Cannot find $lib\n" unless -d $lib;

# (rust name, module, perl hash name)
my @WANTED = (
    ['ID3_GENRE',        'ID3',     'genre'],
    ['MINOLTA_WHITE_BAL','Minolta', 'minoltaWhiteBalance'],
);

my (@out, @skipped);
my $total = 0;

for my $w (@WANTED) {
    my ($rust, $module, $hash) = @$w;
    my $file = "$lib/Image/ExifTool/$module.pm";
    open my $fh, '<', $file or die "Cannot read $file\n";
    my $src = do { local $/; <$fh> };
    close $fh;

    unless ($src =~ /^(?:my\s+)?%$hash\s*=\s*\((.*?)\n\);/ms) {
        push @skipped, "$module: no hash %$hash";
        next;
    }
    my $body = $1;
    my (@rows, @named);
    for my $line (split /\n/, $body) {
        $line =~ s/\s*#.*$//;               # a trailing comment
        next unless $line =~ /\S/;
        # key => 'value'. The key is a number, or a bare word: ID3 gives two of
        # its genres the keys CR and RX.
        unless ($line =~ /^\s*(0x[0-9a-fA-F]+|\d+|\w+)\s*=>\s*'((?:[^'\\]|\\.)*)'\s*,?\s*$/) {
            push @skipped, "$module %$hash: cannot express: $line";
            next;
        }
        my ($k, $v) = ($1, $2);
        $v =~ s/\\'/'/g;
        $v =~ s/\\\\/\\/g;
        $v =~ s/(["\\])/\\$1/g;
        if ($k =~ /^(0x[0-9a-fA-F]+|\d+)$/) {
            push @rows, [$k =~ /^0x/ ? hex($k) : int($k), $v];
        } else {
            push @named, [$k, $v];
        }
        ++$total;
    }
    @rows = sort { $a->[0] <=> $b->[0] } @rows;
    push @out, "/// `%$hash` from $module.pm, as ExifTool defines it.\n"
             . "pub static $rust: &[(i64, &str)] = &[\n"
             . join('', map { sprintf("    (%d, \"%s\"),\n", @$_) } @rows)
             . "];\n";
    if (@named) {
        @named = sort { $a->[0] cmp $b->[0] } @named;
        push @out, "/// The entries of `%$hash` whose key is a word, not a number.\n"
                 . "pub static ${rust}_NAMED: &[(&str, &str)] = &[\n"
                 . join('', map { sprintf("    (\"%s\", \"%s\"),\n", @$_) } @named)
                 . "];\n";
    }
}

my ($ver) = do {
    open my $fh, '<', "$lib/Image/ExifTool.pm" or die $!;
    my $s = do { local $/; <$fh> };
    close $fh;
    $s =~ /\$VERSION\s*=\s*'([^']+)'/ ? $1 : '?';
};

print <<"HEADER";
// \@generated by scripts/gen_conv_tables.pl from ExifTool $ver. DO NOT EDIT.
//
// The lookup hashes ExifTool's named conversion functions read. They are data,
// ported entry by entry; the functions that use them live in tags::conv_expr.

HEADER
print join("\n", @out);

printf STDERR "%d entries in %d tables\n", $total, scalar @out;
if (@skipped) {
    printf STDERR "\n%d entries NOT expressed:\n", scalar @skipped;
    print STDERR "  $_\n" for @skipped;
}
