#!/usr/bin/env python3
"""Turn `parity --dump` TSV into a self-contained parity-report web page.

Reads the TSV (stdin or argv[1]) produced by `cargo run --features parity
--bin parity -- --dump`, and writes a single static HTML page to stdout: a
summary of exiftool-rs vs Perl ExifTool over the whole shipped test corpus,
then one collapsible section per file with a tag-by-tag table and an ISO column.

    parity --dump | python3 scripts/parity_report.py \
        --rs 0.7.3 --exiftool 13.59 > index.html
"""
import argparse
import html
import sys
from collections import OrderedDict

HEADER = "file\ttag\texiftool\texiftool_rs\tiso"


def read_rows(text):
    files = OrderedDict()  # file -> list[(tag, perl, ours, iso)]
    rs_ver = et_ver = ""
    started = False
    for line in text.splitlines():
        if not started:
            # Preamble printed by the binary before the TSV header.
            if line.startswith("Perl ExifTool:"):
                et_ver = line.split(":", 1)[1].split("(")[0].strip()
            elif line.startswith("exiftool-rs:"):
                rs_ver = line.split(":", 1)[1].split("(")[0].strip()
            if line == HEADER:
                started = True
            continue
        parts = line.split("\t")
        if len(parts) != 5:
            continue
        f, tag, perl, ours, iso = parts
        files.setdefault(f, []).append((tag, perl, ours, iso == "1"))
    return files, rs_ver, et_ver


def esc(s):
    return html.escape(s, quote=False)


def render(files, rs_ver, et_ver):
    total_tags = sum(len(v) for v in files.values())
    total_delta = sum(1 for v in files.values() for r in v if not r[3])
    clean_files = sum(1 for v in files.values() if all(r[3] for r in v))
    pct = 100.0 * (total_tags - total_delta) / total_tags if total_tags else 100.0

    out = []
    w = out.append
    w(f"""<!doctype html><html lang="en"><head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>exiftool-rs — ExifTool parity</title>
<style>{CSS}</style></head><body>
<header class="hero">
  <p class="eyebrow">Live differential parity</p>
  <h1>exiftool-rs reads the same as ExifTool</h1>
  <p class="sub">Every tag exiftool-rs extracts from the shipped test corpus, compared
     tag-by-tag against Perl <strong>ExifTool {esc(et_ver)}</strong> — the exact
     bytes both tools print for <code>-s -G1</code>. Regenerated by CI on every push.</p>
  <div class="tiles">
    <div class="tile"><span class="n">{clean_files}/{len(files)}</span><span class="l">files identical</span></div>
    <div class="tile"><span class="n">{total_tags:,}</span><span class="l">tags compared</span></div>
    <div class="tile {'good' if total_delta==0 else 'warn'}"><span class="n">{total_delta}</span><span class="l">deltas</span></div>
    <div class="tile"><span class="n">{pct:.2f}%</span><span class="l">identical</span></div>
  </div>
  <p class="meta">exiftool-rs {esc(rs_ver)} vs ExifTool {esc(et_ver)} · machine-state tags
     (dates, permissions, tool version) excluded · {len(files)} files</p>
</header>
<main>""")

    for f, rows in files.items():
        deltas = sum(1 for r in rows if not r[3])
        ok = deltas == 0
        badge = '<span class="pill good">ISO</span>' if ok else f'<span class="pill warn">{deltas} Δ</span>'
        w(f'<details{"" if ok else " open"}><summary>'
          f'<span class="fname">{esc(f)}</span>'
          f'<span class="cnt">{len(rows)} tags</span>{badge}</summary>')
        w('<div class="scroll"><table><thead><tr><th>Group1:Tag</th>'
          '<th>ExifTool</th><th>exiftool-rs</th><th class="c">ISO</th></tr></thead><tbody>')
        for tag, perl, ours, iso in rows:
            cls = "" if iso else ' class="d"'
            mark = "✓" if iso else "✗"
            w(f'<tr{cls}><td class="t">{esc(tag)}</td><td>{esc(perl)}</td>'
              f'<td>{esc(ours)}</td><td class="c">{mark}</td></tr>')
        w("</tbody></table></div></details>")

    w("</main><footer>Generated from <code>parity --dump</code> · "
      "<a href=\"https://github.com/Le-Syl21/exiftool-rs\">Le-Syl21/exiftool-rs</a></footer>"
      "</body></html>")
    return "".join(out)


CSS = """
:root{
  --bg:#f7f8f6; --panel:#ffffff; --ink:#1a1e1b; --muted:#5c655e; --line:#e2e6e1;
  --accent:#1f8a4c; --accent-soft:#e5f3ea; --warn:#b23b3b; --warn-soft:#f6e5e5;
  --mono:ui-monospace,"SFMono-Regular",Menlo,Consolas,monospace;
  --sans:system-ui,-apple-system,"Segoe UI",Roboto,sans-serif;
}
@media (prefers-color-scheme:dark){:root{
  --bg:#0f130f; --panel:#171c17; --ink:#e7ece7; --muted:#9aa89d; --line:#28302a;
  --accent:#4cc47f; --accent-soft:#15271d; --warn:#e07575; --warn-soft:#2a1717;
}}
:root[data-theme="light"]{--bg:#f7f8f6;--panel:#fff;--ink:#1a1e1b;--muted:#5c655e;--line:#e2e6e1;--accent:#1f8a4c;--accent-soft:#e5f3ea;--warn:#b23b3b;--warn-soft:#f6e5e5;}
:root[data-theme="dark"]{--bg:#0f130f;--panel:#171c17;--ink:#e7ece7;--muted:#9aa89d;--line:#28302a;--accent:#4cc47f;--accent-soft:#15271d;--warn:#e07575;--warn-soft:#2a1717;}
*{box-sizing:border-box}
body{margin:0;background:var(--bg);color:var(--ink);font-family:var(--sans);line-height:1.5;
  font-variant-numeric:tabular-nums}
.hero{max-width:70rem;margin:0 auto;padding:3.5rem 1.5rem 2rem}
.eyebrow{font-family:var(--mono);font-size:.75rem;letter-spacing:.14em;text-transform:uppercase;
  color:var(--accent);margin:0 0 .5rem}
h1{font-size:clamp(1.8rem,4vw,2.7rem);line-height:1.1;text-wrap:balance;margin:0 0 .6rem;font-weight:650}
.sub{max-width:46rem;color:var(--muted);font-size:1.05rem;margin:0 0 1.8rem}
.sub code,.meta code{font-family:var(--mono);font-size:.9em}
.tiles{display:grid;grid-template-columns:repeat(auto-fit,minmax(9rem,1fr));gap:.9rem;margin:0 0 1rem}
.tile{background:var(--panel);border:1px solid var(--line);border-radius:12px;padding:1rem 1.1rem;
  display:flex;flex-direction:column;gap:.15rem}
.tile .n{font-size:1.7rem;font-weight:650;font-family:var(--mono)}
.tile .l{font-size:.8rem;color:var(--muted)}
.tile.good{border-color:var(--accent);background:var(--accent-soft)}
.tile.good .n{color:var(--accent)}
.tile.warn{border-color:var(--warn);background:var(--warn-soft)}
.tile.warn .n{color:var(--warn)}
.meta{color:var(--muted);font-size:.82rem;margin:.4rem 0 0}
main{max-width:70rem;margin:0 auto;padding:1rem 1.5rem 3rem;display:flex;flex-direction:column;gap:.5rem}
details{background:var(--panel);border:1px solid var(--line);border-radius:10px;overflow:hidden}
summary{display:flex;align-items:center;gap:.8rem;padding:.7rem 1rem;cursor:pointer;
  font-family:var(--mono);font-size:.9rem;list-style:none}
summary::-webkit-details-marker{display:none}
summary::before{content:"▸";color:var(--muted);font-size:.8rem}
details[open] summary::before{content:"▾"}
.fname{font-weight:600}
.cnt{color:var(--muted);font-size:.8rem;margin-left:auto}
.pill{font-size:.72rem;padding:.12rem .5rem;border-radius:99px;font-weight:600}
.pill.good{background:var(--accent-soft);color:var(--accent)}
.pill.warn{background:var(--warn-soft);color:var(--warn)}
.scroll{overflow-x:auto;border-top:1px solid var(--line)}
table{border-collapse:collapse;width:100%;font-family:var(--mono);font-size:.82rem}
th,td{text-align:left;padding:.35rem .8rem;border-bottom:1px solid var(--line);
  white-space:nowrap;max-width:32rem;overflow:hidden;text-overflow:ellipsis}
th{position:sticky;top:0;background:var(--panel);color:var(--muted);font-weight:600;
  font-size:.72rem;letter-spacing:.05em;text-transform:uppercase}
td.t{color:var(--accent)}
td.c,th.c{text-align:center;width:3rem}
tr.d td{background:var(--warn-soft)}
tr.d td.c{color:var(--warn);font-weight:700}
footer{max-width:70rem;margin:0 auto;padding:2rem 1.5rem 3rem;color:var(--muted);
  font-size:.82rem;border-top:1px solid var(--line)}
a{color:var(--accent)}
"""


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("tsv", nargs="?", help="TSV file (default: stdin)")
    ap.add_argument("--rs", default="", help="exiftool-rs version")
    ap.add_argument("--exiftool", default="", help="ExifTool version")
    a = ap.parse_args()
    text = open(a.tsv, encoding="utf-8").read() if a.tsv else sys.stdin.read()
    files, rs_ver, et_ver = read_rows(text)
    if not files:
        sys.exit("no data rows found in TSV (missing header?)")
    # Explicit flags override the versions parsed from the dump preamble.
    sys.stdout.write(render(files, a.rs or rs_ver, a.exiftool or et_ver))


if __name__ == "__main__":
    main()
